edgexfoundry/go-mod-core-contracts

- clients/metadata/device_test.go
- models/autoevent.go
- models/autoevent_test.go
- models/device.go
- models/device_test.go
Issues #7 and #14 
NOTE: I went with the property name AutoEvent.Frequency as opposed to AutoEvent.Interval because the new Scheduler contract has an `Interval` type. I thought that using the name Interval here would imply that it was of type `Interval` which is not the case.
> Device support for multiple protocols, auto events

- models/action.go
- models/addressable_test.go
- models/baseobject.go
- models/baseobject_test.go
- models/command.go
- models/command_test.go
- models/describedobject.go
- models/deviceprofile.go
- models/deviceprofile_test.go
- models/deviceresource.go
- models/deviceresource_test.go
- models/get.go
- models/notifications_test.go
- models/profileresource.go
- models/propertyvalue.go
- models/put.go
- models/resourceoperation.go
- models/resourceoperation_test.go
- models/response.go
- models/subscription_test.go
- models/transmission_test.go
- models/units.go
Implements #16.
This is a YAML file before:
```
created: 1551108837189
modified: 1551108837189
origin: 0
description: Example of Simple Device
id: 20128964-ecfd-4c63-a6af-70bcd27f062b
name: Simple-Device
manufacturer: Simple Corp.
model: SP-01
labels: [modbus]
deviceResources:
- description: Switch On/Off.
name: SwitchButton
tag: ""
properties:
value:
type: Bool
readWrite: RW
minimum: ""
maximum: ""
defaultValue: ""
size: ""
mask: ""
shift: ""
scale: ""
offset: ""
base: ""
assertion: ""
precision: ""
units:
type: String
readWrite: R
defaultValue: On/Off
attributes: {}
resources:
- name: Switch
get:
- index: ""
operation: get
object: SwitchButton
parameter: Switch
resource: ""
secondary: []
mappings: {}
set:
- index: ""
operation: set
object: SwitchButton
parameter: Switch
resource: "" …
```
> Empty fields are omitted when marshaling to JSON or YAML a DeviceProfile

- models/interval_action.go
Fix issue #41 
Signed-off-by: Joan Duran <jduran@circutor.com>
> Parameter Path in IntervalAction is marshaled to JSON

- models/propertyvalue.go
- models/propertyvalue_test.go
- models/value-descriptor.go
- models/value-descriptor_test.go
Create "floatEncoding" field to "PropertyValue" and "ValueDescriptor" struct
fix #22
> Create floatEncoding field

- clients/command/client.go
#31 
First small PR towards the above issue. In addition to revising GoDoc content I made some other small changes that are motivating me to check this in by itself.
- Renamed `command/command.go` to `command/client.go` to avoid stutter
- Made the `commandRestClient` unexported as no application should access that type directly
- Revised the parameter names on Get/Put methods to be more descriptive
It appears this client isn't used in either the Device SDK or EdgeX-go. Indeed its current methods don't reflect the full compliment of the CoreCommand API. Inclusion of this client going forward is probably still worthwhile as someone with the need could use it directly and/or extend it to cover the whole CoreCommand API.
> Formatting GoDoc content for CommandClient

- clients/command/client.go
#31 
Follow up to #43 
- I did not modify the parameter names in the actual interface definition per @jduranf 's comment on the previous PR.
- See #core channel in Slack related to local GoDoc review. I have moved the comments for the methods off the implementing type (because they don't show up) to the interface itself.
> Updated GoDoc on Command/Client

- models/autoevent.go
- models/autoevent_test.go
Use duration string for Frequency of AutoEvent
fix #49
> Modify Godoc and data type of AutoEvent.Frequency

- clients/logger/logger.go
- models/addressable.go
- models/addressable_test.go
- models/command.go
- models/command_test.go
- models/describedobject.go
- models/describedobject_test.go
- models/devicereport.go
- models/devicereport_test.go
- models/interval.go
- models/notifications.go
- models/notifications_test.go
- models/provisionwatcher.go
- models/provisionwatcher_test.go
- models/subscription.go
- models/subscription_test.go
- models/timestamps.go
- models/timestamps_test.go
- models/transmission.go
- models/transmission_test.go
Updated all references to BaseObject to now use Timestamps
> Renamed the BaseObject type to Timestamps to better reflect its intent

- models/deviceprofile.go
#59 
New property names were not present in YAML struct tags in PR #61 
> Rename DeviceProfile Resources and Commands (YAML)

- models/commandresponse.go
This is first step toward facilitating the decoupling of the DeviceProfile
and its associated Commands from the Device.
Resolves/Fixes: https://github.com/edgexfoundry/go-mod-core-contracts/issues/68
Related with Issue in edgex-go/core-commands: https://github.com/edgexfoundry/edgex-go/issues/1254
It is preferable both PRs to be mearged at once.
Signed-off-by: difince <dianaa@vmware.com>
> Changing the interface of CommandResponseFromDevice function.

- models/propertyvalue.go
- models/propertyvalue_test.go
- models/value-descriptor_test.go
The value of FloatEncoding field in PropertyValue and
ValueDescriptor is limited to "Base64" and "eNotation"
fix #74
> Add constants for Base64Encoding and eNotation

- models/event.go
- models/event_test.go
- models/reading.go
- models/reading_test.go
This commit fixes issue 76
Updated the struct tags on the Event type. Previously, the id portion of
the struct tag was not specified for the "codec" type, which was causing
issues when encoding and decoding into CBOR using the codec library.
Added "codec" struct tags to the Reading type
Added tests for both types which validates CBOR encoding and decoding
> Fixed Event Struct Tags

- models/deviceresource.go
Replace Attributes data type with map[string]string in DeviceResource
fix #78
> Use string instead of interface{} in Attributes

- clients/coredata/event.go
- clients/coredata/event_test.go
- clients/coredata/reading_test.go
#62 
The Device Services group asked that the EventClient take on the centralized responsibility for handling encoding of events. To that end, marshaling has been exposed to callers via the MarshalEvent method. After the caller uses this method to encode the event, they can add the event directly as a byte array via the new EventClient.AddBytes method.
> Added AddBytes & MarshalEvent methods to EventClient

- models/commandresponse.go
Fix [issue-#91 bug](https://github.com/edgexfoundry/go-mod-core-contracts/issues/91)
the range statement just copy a duplicate value of origin object, so it will not change the origin object
> Fix issue-#91 bug, baseURL is empty when command objecct returns

- models/interval.go
- models/interval_test.go
Fix #1308
Interval's Validate() method was attempting to parse an
integer out of a timestamp. This change has it parsing
a time using the time package's Parse() function.
Signed-off-by: Daniel Harms jdharms@gmail.com
> Fix Interval's Validate() method to check timestamp

- models/value-descriptor.go
- models/value-descriptor_test.go
Fix #119
Add function in value-descriptor.go which handles the creation of a
value descriptor from a device resource.
Add new test to cover newly added functionality.
> Add ValueDescriptor mapping from DeviceResource

- models/resourceoperation.go
- models/resourceoperation_test.go
New fields:
DeviceCommand (json:"deviceCommand")
DeviceResource (json:"deviceResource")
"Object" to be marked as deprecated (replaced by DeviceResource)
"Resource" to be marked as deprecated (replaced by DeviceCommand)
Arrangements to be made in marshaling to duplicate values for compatibility purposes.
fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/114
> Create new fields in ResourceOperation

- models/interval.go
- models/interval_test.go
Fix #138
- Added support for Golang's subsecond patterns "30m10s1000ns"
- Includeds backward compatablity with legacy frequency pattern
- Marshalling/Unmarshalling code updated to reflect the bifurated pattern legacy or golang
Signed-off-by: xmlviking <ecotter@gmail.com>
> Changing interval model to support subsecond frequency time duration

- clients/command/client.go
- clients/command/client_test.go
Fix #141 
Expand CommandClient interface for Put/Get by Names
- Add GetDeviceCommandByNames method to Command client
- Add PutDeviceCommandByNames method to Command client
- Add unit tests for the client
Signed-off-by: Jason Bonafide <jbonafide623@gmail.com>
>  Expand CommandClient interface for Put/Get by Names 

- clients/command/client.go
- clients/command/client_test.go
- clients/coredata/event.go
- clients/coredata/event_test.go
- clients/coredata/reading.go
- clients/coredata/reading_test.go
- clients/coredata/value_descriptor.go
- clients/coredata/value_descriptor_test.go
- clients/endpointer.go
- clients/export/distro/client.go
- clients/general/client.go
- clients/general/client_test.go
- clients/metadata/addressable.go
- clients/metadata/addressable_test.go
- clients/metadata/command.go
- clients/metadata/command_test.go
- clients/metadata/device.go
- clients/metadata/device_profile.go
- clients/metadata/device_profile_test.go
- clients/metadata/device_service.go
- clients/metadata/device_service_test.go
- clients/metadata/device_test.go
- clients/metadata/provision_watcher.go
- clients/metadata/provision_watcher_test.go
- clients/notifications/client.go
- clients/notifications/client_test.go
- clients/scheduler/interval.go
- clients/scheduler/interval_action.go
Fix #150
* Added Fetch method signature to Endpointer interface. This will allow
the immediate retrieval of a service's URL prior to initiating the
monitor goroutine
* The original ask was to facilitate the immediate population of the
GeneralClient's URL. However, given that this is a one line change,
there's no reason to not do the same for the other clients. In this
way an initial call to obtain a service endpoint will be made to the
registry when that communication is enabled.
* Updating unit test mocks with Endpointer.Fetch method
> Add Endpointer.Fetch() method, integrate with Service Clients

- responses/configuration/set.go
- responses/configuration/set_test.go
Fix #152 
- This is a follow up to #128 (External Entity Requests SMA to Set Configuration).
> Remove the field ExpectedValues (from SetConfigResponse) as it is redundant.

- models/autoevent_test.go
- models/callbackalert.go
- models/callbackalert_test.go
- models/channel_test.go
- models/comandresponse_test.go
- models/command.go
- models/command_test.go
- models/commandresponse.go
- models/describedobject.go
- models/device.go
- models/device_test.go
- models/deviceprofile.go
- models/deviceprofile_test.go
- models/deviceservice.go
- models/deviceservice_test.go
Part of the work to address #143
Addresses the following models:
CallbackAlert
Channel
Command
CommandResponse
Device
DeviceProfile
DeviceService
> Update models to serialize zero values as empty JSON objects, part 2

- models/sma_operation.go
- models/sma_operation_test.go
- models/subscription.go
- models/subscription_test.go
- models/timestamps.go
- models/timestamps_test.go
- models/transmission.go
- models/transmission_record.go
- models/transmission_record_test.go
- models/transmission_test.go
- models/units.go
- models/units_test.go
- models/value-descriptor.go
- models/value-descriptor_test.go
Part 3 of 6 for #143
This work includes: sma_operation, subscription, timestamps, transmission, transmission_record, units, value-descriptor
Signed-off-by: Brandon Forster brandonforster@gmail.com
> Update models to serialize zero values as empty JSON objects, part 3

- clients/command/client.go
- clients/command/client_test.go
- clients/coredata/event.go
- clients/coredata/event_test.go
- clients/coredata/reading.go
- clients/coredata/value_descriptor.go
- clients/endpointer.go
- clients/export/distro/client.go
- clients/general/client.go
- clients/general/client_test.go
- clients/metadata/addressable.go
- clients/metadata/command.go
- clients/metadata/device.go
- clients/metadata/device_profile.go
- clients/metadata/device_service.go
- clients/metadata/device_test.go
- clients/metadata/provision_watcher.go
- clients/notifications/client.go
- clients/notifications/client_test.go
- clients/scheduler/interval.go
- clients/scheduler/interval_action.go
Alternate Endpointer contract implementation that encapsulates go routine and stream creation and avoids exposing recently added Fetch() method.
Fixes: https://github.com/edgexfoundry/go-mod-core-contracts/issues/183
Signed-off-by: Michael W. Estrin <me@michaelestrin.com>
> Endpointer Clean Up

- clients/constants.go
Refactoring to move security service keys from edgex-go to go-mod-core contracts.
Addresses https://github.com/edgexfoundry/edgex-go/issues/2174
cc: @michaelestrin
> Refactoring to move security service keys from edgex-go to go-mod-core contracts.

- clients/command/client.go
- clients/coredata/event.go
- clients/coredata/reading.go
- clients/coredata/value_descriptor.go
- clients/general/client.go
- clients/logger/logger.go
- clients/metadata/addressable.go
- clients/metadata/command.go
- clients/metadata/device.go
- clients/metadata/device_profile.go
- clients/metadata/device_service.go
- clients/metadata/provision_watcher.go
- clients/notifications/client.go
- clients/request.go
- clients/scheduler/interval.go
- clients/scheduler/interval_action.go
Fixes #196.
This is the final PR for #196. This PR moves all calls of `URLPrefix` to the `request` package to reduce duplication.
There are two places I would like to call out for special review:
`ValueDescriptorsUsage()` in metadata/provision_watcher.go and
`sendLog()` in `logger/logger.go.
These two functions required me creating a new URLClient that returns an empty string to fulfill the contract and preserve functionality. I did my best, but am not tremendously happy with this solution and would like any suggestions on how to improve it.
> Centralize URLClient logic to the Request package

- clients/scheduler/interval_action_test.go
- clients/scheduler/interval_test.go
While working #196, it was noticed that the scheduler package has no unit tests whatsoever. This PR adds a basic suite of unit tests, taking it from 0% to ~75% coverage.
Dependent on #205.
> Add tests for interval client

- models/reading.go
- models/reading_test.go
Fixes #193.  Add some fields to Reading value as discussed
on 3/2/20 DS Working Group call and documented in discussion
at https://github.com/edgexfoundry/go-mod-core-contracts/issues/193
Signed-off-by: Daniel Harms <jdharms@gmail.com>
The Reading structure is missing a field for Datatype of Sensor Value.
Issue Number:
https://github.com/edgexfoundry/go-mod-core-contracts/issues/193
Reading type has fields for ValueType, FloatEncoding, and MediaType.
> Add ValueType, MediaType, FloatEncoding to Reading

- clients/agent/client.go
Hotfix for this PR: https://github.com/edgexfoundry/go-mod-core-contracts/pull/231
Missed an argument in the interface exported by this package, so the struct exported doesn't properly implement it.  My apologies :(
> Missing argument from interface function in AgentClient

- clients/general/client.go
- clients/general/client_test.go
Fixes #237 
This commit is a partial revert of PR #231. The SMA client remains, but the general client is restored.  I was under the mistaken impression that the SMA client would replace the general client.  This commit fixes the issue.
> Restore clients/general directory

- models/reading.go
- models/reading_test.go
Reading validation enforces a `BinaryValue`(Binary payload) for all readings that are of type `Binary`.
Issue Number: #240 
Reading validation allows for empty `BinaryValue` data(binary reading data).
Validation is more relaxed. However, other modules will need to obtain these changes to be able to properly `Unmarshal` binary `Reading`s and `Event`s that contain binary `Reading`s.
See issue https://github.com/edgexfoundry/edgex-go/issues/2527 for more information.
I tested these changes locally with `edgex-go`, specifically `core-data` to ensure we are able to properly avoid persisting binary readings and still allow the user to obtain the readings and associated events.
This issue is …
> Update Reading Validation-Allow Empty Binary Data

- models/reading.go
- models/reading_test.go
Since Go DS and C DS send reading with different letter cases, we should normalize the valueType to make it consistent.
Go DS and C DS send reading with different letter cases
Issue Number: #243 
Normalize the reading's valueType to the upper camel case.
> feat: Normalize reading's valueType letter case

- clients/scheduler/interval.go
- [X ] Bugfix
go-mod-core-contracts is not compliant with edgex-go about the URL of "remove interval by id" endpoint 
go-mod-core-contract construct the url like this: /api/v1/interval/id/{id}, meanwhile edgex-go exports endpoint  /api/v1/interval/{id}
Issue Number:
https://github.com/edgexfoundry/go-mod-core-contracts/issues/247
Change the URL from /api/v1/interval/id/{id} to /api/v1/interval/{id}
- [X ] No
Signed-off-by: Diana Atanasova <dianaa@vmware.com>
> Fix URL -> Remove Interval By ID

- v2/dtos/reading.go
- v2/dtos/reading_test.go
- v2/dtos/requests/event.go
- v2/dtos/requests/event_test.go
- v2/dtos/responses/event.go
- v2/models/event.go
- v2/models/reading.go
Fix: #251
Issue Number: #251
In Event and Reading, there is a device field. According to Core WG meeting on July 9th 2020, rename to deviceName to make it explicit.
> refactor: Rename device field to deviceName in V2 CoreData DTO and Model

- v2/constants.go
- v2/dtos/common/base.go
- v2/dtos/common/base_test.go
- v2/dtos/common/config.go
- v2/dtos/common/config_test.go
- v2/dtos/common/metrics.go
- v2/dtos/common/metrics_test.go
- v2/dtos/common/ping.go
- v2/dtos/common/ping_test.go
- v2/dtos/common/version.go
- v2/dtos/common/version_test.go
BaseResponse in the common DTOs (Ping, config, metrics, version) is no longer needed 
No common factory methods for created the common DTOs .
Issue Number: #259 
BaseResponse removed from common DTOs.
No common factory methods for created the common DTOs
No
> feat: Update common Response DTOs (Add factory method & remove BaseResponse)

- clients/metadata/device.go
#126  PR Checklist
Device admin and operating status update implementation have been changed
in edgex-go so that the status data is sent in the request body instead of being part of the URL
(see https://github.com/edgexfoundry/edgex-go/pull/1361)
But go-mod-core-contracts wasn't updated accordingly.
So if you try to update admin/operating device state using Device client interface an error "404 page not found" is  returned , because endpoint with such path does not exists
Issue Number:
https://github.com/edgexfoundry/go-mod-core-contracts/issues/272
This PR makes go-mod-core-contracts Device interface compliant with the
implementation within edgex-go.
Signed-off-by: Diana Atanasova …
> Make device client compliant with edgex-go implementation

- models/event.go
- models/event_test.go
- v2/dtos/event.go
- v2/dtos/event_test.go
Go's XML marshal doesn't support maps and throws error when marshaling event due to Tags field.
Issue Number: #276
Disabled XML marshaling of Event Tags field via attribute so error isn't thrown
Add custom ToXML() function that handles the Tags field after marshaling rest of Event fields.
no
no
> fix: Provided custom XML marshaling of Event

- v2/dtos/common/metrics.go
Metrics property on MetricsResonse was in-lined, thus not matching the swagger definition.
Issue Number: #280
Metrics property on MetricsResonse was no longer in-lined, thus it now matches the swagger definition.
No
> fix: Don't in-line `Metrics` property on MetricsResponse so that it matches swagger

- v2/dtos/common/base.go
- v2/dtos/requests/device_test.go
- v2/dtos/requests/deviceservice_test.go
- v2/dtos/requests/event_test.go
In the original implementation, RequestId cannot be empty.
Issue Number: Fix #282 
RequestId can be empty.  If it contains value, it has to be uuid.
> fix: RequestId in V2 API can be empty or uuid

- models/event_test.go
- v2/dtos/event.go
- v2/dtos/reading.go
- v2/dtos/reading_test.go
- v2/dtos/requests/event.go
- v2/dtos/requests/event_test.go
- v2/models/event.go
Event ID can be empty before sending to core-data and assigned in core-data
Issue Number: Fix #287 
Validate Event ID is an UUID and pre-populated
No
No
> Feat (core-data): Event ID has to be UUID and pre-populated

- Dockerfile.build
- Jenkinsfile
- README.md
- go.mod
Updated Dockerfile, go.mod for Go 1.15
Removed go reference in Jenkinsfile so it defaults to CI/CD pipeline default
Updated README Go version references
Fixes: #284
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
- [x ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [x ] Build related changes
- [x ] Other... Please describe:  upgrade to Go 1.15
n/a
Issue Number: #284 
none
- [ x] No
> build: update to go 1.15

- errors/types.go
- errors/types_test.go
errors.CommonEdgeX.Message() might return an empty string if it is just a wrapper.
Issue Number: Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/290
errors.CommonEdgeX.Message() should return the first non-empty message.
> Fix: Error msg should return first non-empty msg

- v2/dtos/requests/event.go
- v2/dtos/requests/event_test.go
event id is always empty when storing into the database.
Issue Number: Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/304
pass event id when converting DTO to model.
modify unit test to verify the id is passed.
> fix (v2dto, data): pass event id from DTO to model

- clients/notifications/client.go
- clients/notifications/client_test.go
ContentType can now be set for notifications when using the REST api
directly, this adds support to the client
Signed-off-by: Alex Ullrich <alexullrich@technotects.com>
Issue Number:
#314 
ContentType available on struct used by notification client
> fix(notifications): add ContentType to client struct

- clients/constants.go
"Correlation-Id" as the http header key
Issue Number: Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/316
Replace CorrelationHeader constant to "X-Correlation-ID" because it is the more common key.
> Fix(all):use "X-Correlation-ID" in header

- v2/dtos/deviceprofile.go
- v2/dtos/requests/deviceprofile.go
- v2/dtos/requests/deviceprofile_test.go
Fix #326
Since community decide to use the PUT instead of the PATCH operation, so it need to modified the struct and related function.
> feat(metadata): Modified deviceProfile DTO to support PUT API

- v2/dtos/responses/event.go
- v2/dtos/responses/event_test.go
Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/330
Rename deviceId to deviceName in EventCountResponse DTO.
> fix: Rename deviceId to deviceName from Event DTO

- v2/dtos/responses/device.go
- v2/dtos/responses/device_test.go
- v2/dtos/responses/deviceprofile.go
- v2/dtos/responses/deviceprofile_test.go
- v2/dtos/responses/deviceservice.go
- v2/dtos/responses/deviceservice_test.go
- v2/dtos/responses/event.go
- v2/dtos/responses/event_test.go
- v2/dtos/responses/reading.go
- v2/dtos/responses/reading_test.go
Per V2 API spec, new response DTOs shall be created to return an array of objects.
- MultiEventsResponse
- MultiReadingsResponse
- MultiDevicesResponse
- MultiDeviceProfilesResponse
- MultiDeviceServicesResponse
Fix: #https://github.com/edgexfoundry/go-mod-core-contracts/issues/332
https://github.com/edgexfoundry/go-mod-core-contracts/issues/332
Add new response DTOs to return an array of objects:
- MultiEventsResponse
- MultiReadingsResponse
- MultiDevicesResponse
- …
> feat(v2dto): Add new Response DTOs to return an array of objects

- errors/types.go
As V2 API supports the pagination through offset and limit query string
when GET multiple objects, there is a need to add new error kind when
the requested range is not satisfiable. For example, when there are only
5 objects in the DB but users requests to retrieve objects starting from
10 (offset=9), V2 API shall return an error kind that such requested
range is not available. This new error kind shall also map to HTTP status
code 416 as indicated in the RFC 7233.
Fix #334 
#334 
A new …
> feat(v2 api): Add new error kind for indicating requested range not satisfiable

- v2/constants.go
GET ALL of V2 API allows users to specify following query strings as part of URL to achieve pagination and query criteria:
- offset: the number of items to skip before starting to collect the result set.
- limit: the numbers of items to return (default:20)
- labels: allows for querying a given object by associated user-defined label. More than one label may be specified via a comma-delimited list
This commit adds constants for these query strings and their default values.
Fix #338 
#338 …
> feat(V2 API): Add new constants and default value for offset, limit, and labels

- v2/constants.go
Per V2 APi spec, more than one label may be specified via a comma-delimited
list. The default separator--comma--should be added as a constant to do the
string split.
Fix #340 
#340 
Per V2 APi spec, more than one label may be specified via a comma-delimited
list. The default separator--comma--should be added as a constant to do the
string split.
No
Are there any specific instructions or things that should be …
> feat(V2 PI): Add new constant for comma separator to split labels

- v2/dtos/event.go
- v2/dtos/requests/event.go
- v2/dtos/responses/event.go
- v2/dtos/responses/event_test.go
#354 
As V2 only allows clients to update event pushed by Id, corresponding DTOs
shall be updated:
UpdateEventPushedByChecksumRequest -> UpdateEventPushedByIdRequest
UpdateEventPushedByChecksumResponse -> UpdateEventPushedByIdResponse
> feat(v2 data): Update DTOs for UpdateEventPushed

- v2/dtos/common/base.go
- v2/dtos/common/base_test.go
- v2/dtos/responses/device.go
- v2/dtos/responses/device_test.go
- v2/dtos/responses/deviceprofile.go
- v2/dtos/responses/deviceprofile_test.go
- v2/dtos/responses/deviceservice.go
- v2/dtos/responses/deviceservice_test.go
- v2/dtos/responses/event.go
- v2/dtos/responses/event_test.go
- v2/dtos/responses/reading.go
- v2/dtos/responses/reading_test.go
Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/342
In 15-OCT-2020 Core WG meeting, we decided to remove all the xxResponseNoMessage helper functions to reduce the future development and unit test effort.
Users could call NewXXResponse with empty string in the message
peremeter instead.
> refactor: remove all ResponseNoMessage funcs in V2

- v2/dtos/autoevent.go
- v2/dtos/command.go
- v2/dtos/device.go
- v2/dtos/deviceprofile.go
- v2/dtos/deviceresource.go
- v2/dtos/deviceservice.go
- v2/dtos/profileresource.go
- v2/dtos/propertyvalue.go
- v2/dtos/requests/device_test.go
- v2/dtos/requests/deviceprofile_test.go
- v2/dtos/requests/deviceservice_test.go
- v2/validator.go
- Update device service with empty name will return status code 404
- It does not allow to update the baseAddress with empty string.
UpdateDeviceDTO and UpdateDeviceServiceDTO should be able to verify the id whether is valid UUID format and the required name should not be empty.
I tried several tag combinations, like,
- required_without and uuid tag
- required_without and gt=0 tag
- required_without and omitempty and uuid tag
- required_without and omitempty and gt=0 tag
But it didn't pass expected test cases:
- When Id …
> fix(metadata): Add validation tag for UpdateDTO

- errors/types.go
- v2/clients/http/common.go
- v2/clients/http/common_test.go
- v2/clients/http/utils/common.go
- v2/clients/http/utils/get.go
- v2/clients/interfaces/common.go
No V2 CommonClient for calling operational endpoints that are present on all service V2 APIs.
V2 CommonClient provides a client for calling the following operational endpoints that are present on all service V2 APIs:
- /config
- /metrics
- /ping
- /version
> feat(clients): Add V2 CommonClient

- v2/clients/http/event.go
- v2/clients/http/event_test.go
- v2/clients/http/utils/post.go
- v2/clients/interfaces/event.go
There is no V2 EventClient.
Added the V2 EventClient and implemented the Add method, which is used to issue an HTTP POST request to the core-data service to add new events. This PR also introduced the HTTP POST helper function for V2 clients.
> feat(clients): Implement Add method for V2 EventClient

- v2/dtos/common/count.go
- v2/dtos/common/count_test.go
- v2/dtos/responses/event.go
- v2/dtos/responses/event_test.go
- v2/dtos/responses/reading.go
- v2/dtos/responses/reading_test.go
The original V2 API design defines both `EventCountResponse` and `ReadingCountResponse` with exactly identical schema. These two responses seems to be redundant.
Moreover, field `deviceName` inside `EventCountResponse` seems to be redundant as a GET /event/count/device/{deviceName} request will include deviceName as part of route.
fix #376 
This PR implement a new `CountResponse` to replace these two count responses.  The new `CountResponse` also ditch `deviceName` field.
> feat: Add a new CountResponse to replace EventCountResponse and ReadingCountResponse

- v2/dtos/deviceservice.go
- v2/dtos/requests/deviceservice.go
- v2/dtos/requests/deviceservice_test.go
- v2/models/deviceservice.go
Discussed in the Device WG meeting on 5th-Oct-2020, the OperatingState field in DeviceService model is not used. Its status should be monitored via health check like other services in general, so it is not necessary to manage it in core-metadata.
Fix #319
Remove OperatingState field in DeviceService V2 model
> refactor(meta): Remove OperatingState field in DeviceService V2 model

- v2/dtos/device.go
- v2/dtos/deviceservice.go
- v2/dtos/requests/device_test.go
- v2/dtos/requests/deviceservice.go
- v2/dtos/requests/deviceservice_test.go
- v2/models/deviceservice.go
- v2/models/operatingstate.go
Fix #318 
V2 Device OperatingState value change the enumeration value of OperatingState from Enabled/Disabled to Up/Down/Unknown
This PR is based on the https://github.com/edgexfoundry/go-mod-core-contracts/pull/384
> refactor(meta): V2 Device OperatingState value change

- v2/clients/http/common.go
- v2/clients/http/deviceprofile.go
- v2/clients/http/deviceprofile_test.go
- v2/clients/http/utils/request.go
- v2/clients/interfaces/deviceprofile.go
Fix #392
Add V2 client for querying the device profile
- query by name
- query all
- query all by model
- query all by manufacturer
- query all by manufacturer and model
> feat(meta): Add V2 client for querying device profile

- v2/constants.go
- v2/dtos/event.go
- v2/dtos/event_test.go
- v2/dtos/requests/event.go
- v2/dtos/responses/event.go
- v2/dtos/responses/event_test.go
- v2/models/event.go
fix #397 
Per edgexfoundry/edgex-go#2937, Event DTO/Model no longer needs pushed field,
so remove pushed field for code purity.
> feat(v2 data): Remove pushed field from Event DTO/Model

- v2/dtos/command.go
- v2/dtos/device.go
- v2/dtos/deviceprofile.go
- v2/dtos/deviceresource.go
- v2/dtos/deviceservice.go
- v2/dtos/event.go
- v2/dtos/profileresource.go
- v2/dtos/reading.go
- v2/dtos/requests/const_test.go
- v2/dtos/requests/device_test.go
- v2/dtos/requests/deviceprofile_test.go
- v2/dtos/requests/deviceservice_test.go
- v2/dtos/requests/event_test.go
- v2/validator.go
fix #343 
Implement a new custom validation tag "edgex-dto-rfc3986-unreserved-chars" to ensure name fields only allows RFC3986 unreserved characters.
There is no suitable existing validation tag to satisfy our needs, so I have to implement a custom tag `edgex-dto-rfc3986-unreserved-chars` to verify that all V2 DTOs' name fields could only contain unreserved characters as defined in https://tools.ietf.org/html/rfc3986#section-2.3.  Please note that unreserved characters= ALPHA / DIGIT / "-" / "." / "_" / "~"
> feat(v2): implement custom validation tag for RFC3986 unreserved characters

- v2/clients/http/device.go
- v2/clients/http/device_test.go
- v2/clients/http/utils/request.go
- v2/clients/interfaces/device.go
fix #403 
Add V2 DeviceClient for interactions with V2 Device endpoint on the core-metadata service.
- (POST) /device
- (PATCH) /device
- (GET) /device/all
- (GET) /device/check/name/{name}
- (GET) /device/name/{name}
- (DELETE) /device/name/{name}
- (GET) /device/profile/name/{name}
- (GET) /device/service/name/{name}
> feat(meta): Add V2 DeviceClient

- v2/clients/http/deviceservice.go
- v2/clients/http/deviceservice_test.go
- v2/clients/interfaces/deviceservice.go
fix: #407 
Add V2 DeviceServiceClient for interactions with V2 Device Service endpoint on the core-metadata service.
- (POST) /deviceservice
- (PATCH) /deviceservice
- (GET) /deviceservice/all
- (GET) /deviceservice/name/{name}
- (DELETE) /deviceservice/name/{name}
> feat(meta): Add DeviceServiceClient

- v2/dtos/requests/event.go
- v2/dtos/requests/event_test.go
fix #429
Per discussion over edgexfoundry/edgex-go#3002 (comment), AddEvent V2 API shall be updated to deal with single AddEventRequest DTO instead of AddEventRequest DTO array. As a result, func `AddEventReqToEventModels` shall be updated accordingly.
> feat(data): Update AddEvent to use single AddEventRequest DTO

- v2/clients/http/event.go
- v2/clients/http/event_test.go
- v2/clients/interfaces/event.go
fix: #415 
The current V2 EventClient only supports adding events.
Complete the V2 EventClient for interactions with the V2 Event endpoint on the Core Data Service.
- (POST) /event
- (GET) /event/all
- (GET) /event/count
- (GET) /event/count/device/name/{name}
- (GET) /event/device/name/{name}
- (DELETE) /event/device/name/{name}
- (GET) /event/start/{start}/end/{start}
- (DELETE) /event/age/{age}
> feat(meta): Complete the EventClient

- v2/validator.go
Enhance V2 validation error message to contain the parent struct name.
Fix #437
Signed-off-by: Lindsey Cheng <beckysocute@gmail.com>
Currently the error message defined for V2 DTO validation only contains the struct field name and field value, so it would be out of track in which struct name the field failed the validation, Ex. The error message `Type field is required` does not indicate in which struct has the field `Type`.
#437
The error message contains the (parent) struct name as well as the field name, ex. …
> feat: Enhance V2 validation error message

- v2/constants.go
- remove command by id route
- update callback by id route to callback by name
The device service v2 api route are outdated.
update the device service v2 api route per latest device WG's discussion
> feat: update device service v2 api route

- v2/clients/http/provisionwatcher.go
- v2/clients/http/provisionwatcher_test.go
- v2/clients/interfaces/provisionwatcher.go
add v2 ProvisionWatcherClient to interact with v2 ProvisionWatcher
endpoint on the core-metadata service.
- (POST)   /provisionwatcher
- (PATCH)  /provisionwatcher
- (GET)    /provisionwatcher/all
- (GET)    /provisionwatcher/name/{name}
- (GET)    /provisionwatcher/service/name/{name}
- (GET)    /provisionwatcher/profile/name/{name}
- (DELETE) /provisionwatcher/name/{name}
add v2 ProvisionWatcherClient
Are there any specific instructions or things that should be known prior to …
> feat(meta): implement ProvisionWatcherClient

- v2/constants.go
- v2/dtos/command.go
- v2/dtos/corecommand.go
- v2/dtos/deviceprofile.go
- v2/dtos/responses/corecommand.go
- v2/dtos/responses/corecommand_test.go
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-command/2.x#/CommandResponse defines array of CommandResponse DTO as the response for GET /device/all and single CommnadResponse DTO as response for GET /device/name/{name}. After discussion with Cloud, this structure could be simplified by moving device field into CoreCommand DTO, and then both GET /device/all and GET /device/name/{name} could have single CommandResponse with multiple CoreCommand DTOs. Moreover, with such …
> feat(command): Revise CommandResponse DTO to MultiCoreCommandsResponse

- v2/clients/http/deviceservicecallback.go
- v2/clients/http/deviceservicecallback_test.go
- v2/clients/interfaces/deviceservicecallback.go
- v2/constants.go
- update DELETE callback to be done by name
- add ProvisionWatcher callback support
- add DeviceProfile callback support
DeviceServiceCallbackClient is now able to fully utilize device service v2 callback API
> feat: enhance v2 DeviceServiceCallbackClient

- errors/types.go
- v2/clients/http/utils/common.go
The sendRequest function doesn't return a proper EdgeX ErrKind when request fails.
Added a `KindMapping` function for determining the correct EdgeX ErrKind for the given HTTP status code.
Updated V2 HTTP sendRequest function to return the correct EdgeX ErrKind when request fails.
Close #444
Refer to [codeMapping](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/errors/types.go#L187-L214) function, there is a many-to-one relationship between some EdgeX ErrKinds and HTTP status codes. Reverse mapping seems …
> feat: Refactor HTTP sendRequest function

- v2/dtos/common/base.go
- v2/dtos/common/base_test.go
- v2/dtos/common/secret_test.go
- v2/dtos/event.go
- v2/dtos/event_test.go
- v2/dtos/reading.go
- v2/dtos/reading_test.go
- v2/dtos/requests/device_test.go
- v2/dtos/requests/deviceprofile_test.go
- v2/dtos/requests/deviceservice_test.go
- v2/dtos/requests/event.go
- v2/dtos/requests/event_test.go
- v2/dtos/requests/interval_test.go
- v2/dtos/requests/provisionwatcher_test.go
AddEventRequest, Event and Reading DTOs do not have factory methods
AddEventRequest, Event and Reading DTOs now have factory methods
> feat: Add factory methods for AddEventRequest, Event and Reading DTOs

- v2/dtos/device.go
- v2/dtos/deviceprofile.go
- v2/dtos/deviceprofile_test.go
- v2/dtos/deviceservice.go
- v2/dtos/event.go
- v2/dtos/interval.go
- v2/dtos/reading.go
ApiVersion not being set on all ToDto helper functions.
ApiVersion now being set on all ToDto helper functions that have ApiVersion
> fix: Ensure ApiVersion is set when converting models to DTOs

- v2/clients/http/deviceservicecommand.go
- v2/clients/http/deviceservicecommand_test.go
- v2/clients/interfaces/deviceservicecommand.go
- v2/clients/interfaces/mocks/DeviceServiceCommandClient.go
fix #479 
The original DeviceServiceCommandClient interface will use baseUrl as the object field; however, as various device services will have different baseUrl, so we shall move the baseUrl from object field to the parameters of func GetCommand and SetCommand. With such change, a single DeviceServiceCommandClient could interact with various device services.
> feat(v2): Adjust DeviceServiceCommandClient interface by moving baseURL as func param

- v2/dtos/common/base.go
- v2/dtos/deviceprofile.go
- v2/dtos/deviceprofile_test.go
Fix #483
Miss the apiVersion after unmarshaling by yaml lib.
To fix the device profile YAML file post fail, add apiVersion yml tag for unmarshaling.
> fix(meta): Add yml tag for device profile API

- v2/clients/http/deviceservicecommand.go
- v2/clients/http/deviceservicecommand_test.go
- v2/clients/interfaces/deviceservicecommand.go
- v2/clients/interfaces/mocks/DeviceServiceCommandClient.go
fix #485 
The current DeviceServicCommandClient interface only specify pushEvent and returnEvent as part of func GetCommand signature, which is not properly handling user specified query parameters. The DeviceServicCommandClient interface shall update its GetCommand signature to have queryParams so that all query params could be passed to device service for further processing.
> feat(v2): Update DeviceServiceCommandClient interface to have queryParams

- v2/dtos/deviceprofile.go
- v2/dtos/deviceprofile_test.go
- v2/dtos/propertyvalue.go
- v2/dtos/requests/deviceprofile.go
- v2/dtos/requests/deviceprofile_test.go
- v2/models/propertyvalue.go
Close #289
- Profile DTO add UnmarshalYAML func for POST /deviceprofile/uploadfile API
- Rename PropertyValue's Type field to ValueType.
> refactor(meta): Profile add UnmarshalYAML func and rename Type field

- v2/dtos/requests/event.go
- v2/dtos/requests/event_test.go
update the function name and the parameter to accept a single EventDTO
`NewAddEventRequest` factory method now accept a whole EventDTO
> refactor(data): update NewAddEventRequest factory method

- v2/dtos/requests/subscription.go
- v2/dtos/requests/subscription_test.go
ReplaceSubscriptionModelFieldsWithDTO function is missing the process of replacing the ResendLimit and ResendInterval fields.
Added replacements of the ResendLimit and ResendInterval fields.
Close #500
> fix(v2): Refine the ReplaceSubscriptionModelFieldsWithDTO func

- v2/dtos/corecommand.go
- v2/dtos/responses/corecommand.go
- v2/dtos/responses/corecommand_test.go
fix #506 
The original CoreCommand DTO has field "DeviceName" to indicate which
device the command belongs to; however, the "DeviceName" becomes
redundant when query commands by deviceName, as each CoreCommand DTO
returned includes the same value of DeviceName.  As a result, this
commit refactor the CoreCommand DTO by extracting DeviceName up to a
level, so a single new DeviceCoreCommand DTO will have DeviceName and
ProfileName on the top level, and multiple CoreCommands in the bottom
level.
> feat(v2): refactor CoreCommand DTO to DeviceCoreCommand

- v2/dtos/event_test.go
- v2/dtos/reading.go
- v2/dtos/reading_test.go
Floats are being Base64 encoded
Floats are now E-Notation encoded
> fix: Fix float reading encoding to be simple E-Notation

- v2/dtos/requests/subscription_test.go
- v2/dtos/subscription.go
Both `Categories` and `Labels` fields are required when adding a new Subscription.
Added `omitempty` after `required_without` so that the validator can work as expected.
Close #515
> fix(v2): Add missing validation tag to Subscription DTO

- v2/constants.go
Create Primary and Password for configuration's map key
> feat: Create Constants for configuration's map key

- v2/clients/http/utils/common.go
- v2/dtos/device.go
- v2/dtos/device_test.go
- v2/dtos/deviceservice.go
- v2/dtos/deviceservice_test.go
- v2/dtos/provisionwatcher.go
- v2/dtos/provisionwatcher_test.go
- v2/dtos/reading.go
Fix #528
1. Check the empty value when convert Model to UpdateDTO
- FromProvisionWatcherModelToUpdateDTO
- FromDeviceModelToUpdateDTO
- FromDeviceServiceModelToUpdateDTO
2. API client lib handle the 404 StatusNotFound response
3. Modify BinaryReading validate annotation
> fix: Check empty value when converting Model to UpdateDTO

- v2/dtos/notification.go
- v2/dtos/notification_test.go
- v2/dtos/requests/notification_test.go
Signed-off-by: Felix Ting <felix@iotechsys.com>
Added factory method for Notification DTO.
Close #530
> feat(notifications): Add factory method for Notification DTO

- errors/types.go
Add new ErrKind used for device service data transformation
> feat: add error type used by device service data transformation

- v2/dtos/address.go
- v2/dtos/intervalaction.go
- v2/dtos/requests/intervalaction.go
- v2/dtos/requests/intervalaction_test.go
- v2/models/intervalaction.go
Close #535
Since the common Address created, we can add it to the IntervalAction model and DTO.
> feat: Update IntervalAction to use the common Address

- v2/dtos/device.go
- v2/dtos/deviceprofile.go
- v2/dtos/deviceprofile_test.go
- v2/dtos/deviceservice.go
- v2/dtos/interval.go
- v2/dtos/intervalaction.go
- v2/dtos/notification.go
- v2/dtos/notification_test.go
- v2/dtos/provisionwatcher.go
- v2/dtos/requests/device.go
- v2/dtos/requests/device_test.go
- v2/dtos/requests/deviceprofile.go
- v2/dtos/requests/deviceprofile_test.go
- v2/dtos/requests/deviceservice.go
- v2/dtos/requests/deviceservice_test.go
- v2/dtos/requests/interval.go
- v2/dtos/requests/interval_test.go
- v2/dtos/requests/intervalaction.go
- v2/dtos/requests/notification.go
- v2/dtos/requests/provisionwatcher.go
- v2/dtos/requests/provisionwatcher_test.go
- v2/dtos/requests/subscription.go
- v2/dtos/requests/subscription_test.go
- v2/dtos/subscription.go
Close #537
The apiVersion is required.
- Remove the required validation tag from apiVersion.
- Check the requestDTOs and EventDTO which should contains valid api version
> refactor: Remove ApiVersion from normal DTOs except EventDTO

- v2/constants.go
- v2/dtos/address.go
- v2/dtos/address_test.go
- v2/dtos/requests/subscription.go
- v2/dtos/requests/subscription_test.go
- v2/dtos/subscription.go
- v2/models/subscription.go
Subscription Channel is of type Address.
Close #545
> feat(notifications): Update Subscription DTO to adopt common Address

- v2/dtos/address.go
- v2/models/address.go
- v2/models/const_test.go
- v2/models/intervalaction.go
- v2/models/intervalaction_test.go
- v2/models/subscription.go
- v2/models/subscription_test.go
Close #554
JSON unmarshal fun can't unmarshal the interface type.
Add custom function for IntervalAction and Subscription model to unmarshal the Address.
> fix: Add Address model unmarshal func

- v2/clients/http/device.go
- v2/clients/http/deviceprofile.go
- v2/clients/http/deviceservice.go
- v2/clients/http/deviceservicecallback.go
- v2/clients/http/event.go
- v2/clients/http/provisionwatcher.go
- v2/clients/http/utils/common.go
- v2/clients/http/utils/request.go
- v2/dtos/requests/event.go
- revert #550
- add utils functions to create request and post request with encoded data
the encoding logic is in `EventClient`, which cannot be reused by Device-SDK
prerequisite of https://github.com/edgexfoundry/device-sdk-go/issues/688
encoding logic is now under `AddEventRequest` and can be reused by Device-SDK
> feat: add encoding method for AddEventRequest

- go.mod
- v2/dtos/address.go
- v2/dtos/address_test.go
Close #557
JSON marshal result contains other address's empty fields.
- Upgrade the github.com/go-playground/validator lib to v10.4.1 to apply the new validation tag
- Address add JSON omitempty tag to omit the empty values from other address types.  The issue can refer to https://github.com/edgexfoundry/edgex-go/issues/3294
- Add EmailAddress struct to DTO to consistent with other address types
- Rename the DTO's emailAddresses to recipients to consistent with model
Are there any specific instructions or things that should …
> feat: Address add json omitempty and emailAddress struct to DTO

- v2/clients/http/deviceservicecommand_test.go
- v2/dtos/event.go
- v2/dtos/event_test.go
- v2/dtos/reading.go
- v2/dtos/reading_test.go
- v2/dtos/requests/event_test.go
- v2/models/event.go
- v2/models/reading.go
Close #553
In March-18-2021 Core WG meeting, we decided to remove created field from Event and Reading
> feat: Remove created field from Event and Reading

- v2/dtos/dbtimestamp.go
- v2/dtos/device.go
- v2/dtos/deviceprofile.go
- v2/dtos/deviceservice.go
- v2/dtos/interval.go
- v2/dtos/intervalaction.go
- v2/dtos/notification.go
- v2/dtos/provisionwatcher.go
- v2/dtos/subscription.go
- v2/models/dbtimestamp.go
- v2/models/device.go
- v2/models/deviceprofile.go
- v2/models/deviceservice.go
- v2/models/interval.go
- v2/models/intervalaction.go
- v2/models/intervalaction_test.go
- v2/models/notification.go
- v2/models/provisionwatcher.go
- v2/models/subscription.go
Close #560
For reusing the Created and Modified fields, extract these fields to a single struct.
- Rename the Timestamps to DBTimestamp
- Refactor DTO's Created and Modified field to DBTimestamp struct
> refactor: Refactor DTO's Created and Modified field to DBTimestamp

- v2/dtos/requests/subscription_test.go
- v2/dtos/subscription.go
Close #565
Add validation tag `gt=0` to verify subscription:
- empty Channels should be invalid
- nil Channels should be valid
> fix: Add validation tag to verify subscription with empty Channels

- v2/dtos/common/base.go
- v2/dtos/common/base_test.go
Close #567
- Add omitempty json tag to RequestId
- Message use string instead of interface{} data type
> feat(v2): BaseResponse omit empty RequestId and Message

- v2/dtos/requests/subscription.go
- v2/dtos/requests/subscription_test.go
Close #569
UpdateSubscriptionRequest accept empty categories and labels.
UpdateSubscriptionRequest verify the categories and labels which can not be both empty
> feat: Return 400 when UpdateSubscription with empty categories and labels

- errors/types.go
`errors.NewCommonEdgexWrapper` is used to record the function call stacks, it doesn't add additional error/info message:
https://github.com/edgexfoundry/go-mod-core-contracts/blob/9675502d886e98cc9b362e5032cc42b972c2765c/errors/types.go#L164-L174
If the returning error is wrapped by multiple `errors.NewCommonEdgexWrapper` calls, the error message is a bit confusing:
```
level=ERROR ts=2021-04-01T04:02:20.277154Z app=device-simple source=init.go:76 msg="Failed to create the …
```
> fix: remove unnecessary arrow sign in error message

- v2/dtos/reading.go
- v2/dtos/reading_test.go
String value for float arrays is missing the ending ']'
String value for float arrays now have the ending ']'
> fix: Add the missing ending ']' for float arrays

- v2/clients/constants.go
- v2/clients/http/deviceservicecommand.go
- v2/clients/http/utils/common.go
- v2/clients/http/utils/request.go
- v2/dtos/address_test.go
- v2/dtos/requests/event.go
- v2/dtos/responses/event.go
Close #596
Fix the ambiguous import that is referencing either V1 clients or V2 clients from V1 Modules.
> fix: Fix ambiguous import path for V2 module

- v2/constants.go
- v2/dtos/responses/health.go
- v2/dtos/responses/health_test.go
example result of the HealthResponse:
```
{
apiVersion: "v2"
message: "message"
statusCode: 200
health: {
edgex-core-command: "healthy"
edgex-core-data: "healthy"
support-scheduler: "support-scheduler service is not registered. Might not have started... "
}
```
> feat: add HealthResponse for SMA GET health API

- v2/dtos/corecommand.go
- v2/dtos/responses/corecommand_test.go
Close #574
Add a field called parameters to Core Command. For Get command, it describes the expected readings. For Set command, it describes the parameters in the payload.
> feat: Add parameters field to Core Command

- clients/constants.go
Service key constants have the `edgex-` prefix
Service key constants no longer have the `edgex-` prefix
BREAKING CHANGE: Service key names have changed.
> refactor: Remove edgex-prefix from all service keys

- v2/constants.go
- v2/dtos/common/base.go
- v2/dtos/common/config.go
- v2/dtos/common/config_test.go
- v2/dtos/common/metrics.go
- v2/dtos/common/metrics_test.go
pre-requisite of https://github.com/edgexfoundry/edgex-go/issues/3524
Because SMA original `api/v2/metrics` API is collided with each service's common API, update the SMA v2 API to have `api/v2/system` route prefix.
example of new sma v2 API:
```
$curl http://localhost:58890/api/v2/system/health?services=core-data,core-metadata
207
[
{
"apiVersion": "v2",
"message": "core-data service is not registered. Might not have started... ",
"statusCode": 404,
"serviceName": "core-data" …
```
> feat: prepare new route and DTO for SMA v2 redesign

- v2/dtos/interval.go
- v2/dtos/requests/const_test.go
- v2/dtos/requests/interval.go
- v2/dtos/requests/interval_test.go
- v2/models/interval.go
Close #629
Remove the runOnce field from the Interval model and DTO according to the issue edgexfoundry/edgex-go#3532.
> refactor: Remove runOnce from the Interval

- common/validator.go
- dtos/requests/const_test.go
Name validator allows the "." character which causes issues when the name with a "." is used in the publish topic with Redis.
Name validator no longer allows the "." character
> fix: Update name validator to not allow the "." character

- clients/http/deviceprofile_test.go
- clients/http/utils/common.go
- errors/types.go
Close #645
- Remove the 0 status code
- KindIOError uses 403 as the status code
> feat: Remove unclear HTTP status code

- dtos/device.go
- dtos/deviceservice.go
- dtos/interval.go
- dtos/provisionwatcher.go
Close #652
Add DBTimestamp for device, deviceService, interval, provisionwatcher Model when converting to DTO.
> fix: Add missing DBTimestamp for Model To DTO conversion

- dtos/reading.go
Close #650
Since BaseReading DTO contains SimpleReading and BinaryReading, so the query result will show empty value or null value in reading DTO for different valueType like:
- { "valueType":"Binary", "binaryValue":"...", "value":"" }
- { "valueType":"Int32", "binaryValue":null, "value":"123" }
To resolve it, add omitempty tag to SimpleReading and BinaryReading DTO.
> feat: Add omitempty tag To Reading DTO

- clients/http/deviceservicecommand_test.go
- dtos/event.go
- dtos/event_test.go
- dtos/requests/event.go
- dtos/requests/event_test.go
- models/event.go
- change map[string]string to map[string]interface{} to meet more user requirement.
- The string can still be used in the Tag. It's backward compatible.
Closes #661
https://github.com/edgexfoundry/edgex-go/pull/3727
1. Modify the edgex-go's go.mod to replace the core-contracts lib
2. Run core-data
3. Add event and query event to see the change
> feat(data): Use generic interface in the Event Tagging value

- common/constants.go
- common/utils.go
- dtos/deviceprofile.go
- dtos/deviceprofile_test.go
- dtos/event.go
- dtos/event_test.go
- dtos/reading.go
- dtos/reading_test.go
- models/reading.go
Add a new valueType "Object" and ObjectReading with an "objectValue" field in interface data type.
Closes #665
1. Modify core-data and device simple to use specified core-contracts
2. Execute read command and the reading should contain Object value type like :
```
"readings": [
{
"id": "a8c52c7e-394b-46e1-bf2c-cda9b9e52c56",
"origin": 1633336444179642000,
"deviceName": "Simple-Device01",
"resourceName": "Counter",
"profileName": "Simple-Device",
"valueType": "Object", …
```
> feat: Support object value type in Reading

- dtos/requests/const_test.go
- dtos/requests/intervalaction.go
- dtos/requests/intervalaction_test.go
Closes #682
Run the unit test to check whether the value is changed as expected.
> fix: Fix wrong intervalAction field assignment

- dtos/address.go
- dtos/address_test.go
Adding the PATCH method to Address DTO validate tag
Fix #685
Fork the branch and run the unit test.
> fix: Adding the missed PATCH method in REST Address DTO

- README.md
- go.mod
Changes related to Go 1.17 module changes
> ci: gomod changes related for Go 1.17

- dtos/common/config.go
- dtos/common/config_test.go
- dtos/common/metrics.go
- dtos/common/metrics_test.go
- dtos/common/ping.go
- dtos/common/ping_test.go
- dtos/common/version.go
- dtos/common/version_test.go
Uses new method to optionally create with name.
Fixes #696 
Signed-off-by: Alex Ullrich <alex.ullrich@gmail.com>
unit test sufficient
not sure if docs change needed until used in SDK(s)
> feat: Add ServiceName to Common DTOs

- dtos/deviceprofile.go
- dtos/requests/deviceprofile_test.go
build metadata docker image based on this branch, and POST /deviceprofile with empty devcieResources and deviceCommands, also open PR for TAF tests https://github.com/edgexfoundry/edgex-taf/pull/614
> feat: Remove DeviceProfile deviceResources validate gt=0

- clients/http/command.go
- clients/http/command_test.go
- clients/interfaces/command.go
add 'IssueGetCommandByNameWithQueryParams' method to allow the user
query parameters to be added to the Get command request.
fixes #713
1. use `CommandClient` from this branch and verify the new method is working
> feat: add new method for CommandClient

- clients/http/command.go
- clients/http/common.go
- clients/http/device.go
- clients/http/deviceprofile.go
- clients/http/deviceservice.go
- clients/http/deviceservicecallback.go
- clients/http/deviceservicecommand.go
- clients/http/event.go
- clients/http/interval.go
- clients/http/intervalaction.go
- clients/http/notification.go
- clients/http/provisionwatcher.go
- clients/http/reading.go
- clients/http/subscription.go
- clients/http/system.go
- clients/http/transmission.go
- clients/http/utils/common.go
- clients/http/utils/request.go
- clients/interfaces/mocks/CommandClient.go
- Remove redundant URL escaping from Client lib
- Refactor the HTTP request creating func
Close #730
1. Run go-mod-core-contract unit test
2. Deploy EdgeX
3. Deploy simple device service
4. Test Set and Get command to verify the general function works.
> fix: Remove redundant URL escaping from Client lib

- dtos/reading.go
- dtos/reading_test.go
close #737
1. Build core-data from this branch and run with other edgex services
2. Create a event having mismatched value and valueType
3. verify the response
> feat: Add SimpleReading value validation to prevent type mismatch

- common/constants.go
refactor: Adding Config Stem Constants 
Added constants to be common that are previously defined only in edgex-go.
Closes: #754
- [ x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ x] I am not introducing a new dependency (add notes below if you are)
> refactor: adding config stem constants

- common/validator.go
Add characters :;= to reduce the character restriction.
Add characters :;= to reduce the character restriction.
- In BACNet protocol, the user might combine object type and property as the resourceName, for example, analog_input_0:present-value
- In OPC_UA protocol, the user might use NodeId as the resourceName, for example, ns=10;s=Hello:World
Close #750
- Run core-metadata
- Add metadata with characters :;=
> feat: Reduce the character restriction of the name field

- common/constants.go
BREAKING CHANGE: Location of service configuration in Config Provider (Consul) has changed
closes #775
This PR goes hand in hand with https://github.com/edgexfoundry/go-mod-bootstrap/pull/401
> refactor!: Change Config stem constants to flatten config layout

- clients/http/command.go
- clients/http/command_test.go
- clients/interfaces/command.go
- common/constants.go
BREAKING CHANGE:
- ds-pushevent and ds-returnevent to use true/false instead of yes/no
close #780
https://github.com/edgexfoundry/edgex-docs/pull/917
build core-command and device-virtual docker images based on the changes and run docker-compose.yml
The following commands work as expected:
- `curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-pushevent\=true`
- `curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-pushevent\=false`
- …
> refactor!: Use true/false for command parameters to be more consistent

- common/constants.go
Topic constants for commanding were scattered across multiple files. This puts them in a single place.
> feat: Consolidate topic keys for Commanding in one block of common constants

- dtos/device.go
- dtos/device_test.go
- dtos/requests/device.go
- dtos/requests/device_test.go
- models/device.go
Add an extendable field into Device DTO and Model: Properties map[string]any
This is useful for some devices that requires extra information. For example, a BACnet device may have properties such as DeviceInstance, Firmware, InstanceID, and ObjectName.
fixes https://github.com/edgexfoundry/go-mod-core-contracts/issues/769
> feat: Add new Properties field to Device DTO and Model

- dtos/device.go
- dtos/device_test.go
- dtos/deviceservice.go
- dtos/requests/device.go
- dtos/requests/device_test.go
- dtos/requests/deviceservice.go
- models/device.go
- models/deviceservice.go
BREAKING CHANGE: remove LastConnected and LastReported from device and device service DTOs and models
close #771
https://github.com/edgexfoundry/edgex-docs/pull/965
> feat!: Remove LastConnected and LastReported from Device/DeviceService

- dtos/provisionwatcher.go
- dtos/provisionwatcher_test.go
- dtos/requests/provisionwatcher.go
- dtos/requests/provisionwatcher_test.go
- models/provisionwatcher.go
Add an extendable field into ProvisionWatcher DTO and Model: `Properties map[string]any`. This is useful when certain device services requires extra information from ProvisionWatcher.  For example, assume a device service would like to generate the device name in certain format during auto discovery, the user can define a property "DeviceNameTemplate" with value as the template of device name in the ProvisionWatcher, so that the device service can pick up such property to generate the device name.
fixes https://github.com/edgexfoundry/go-mod-core-contracts/issues/772
Please check if your PR …
> feat: Add new Properties field to ProvisionWatcher DTO and Model

- dtos/deviceprofile_test.go
- dtos/resourceproperties.go
- models/resourceproperties.go
also add 'omitempty' JSON tag for non-required properties
closes #770
> feat: add 'Others' field in ResourceProperties

- dtos/device.go
- dtos/requests/device.go
- dtos/requests/device_test.go
- models/device.go
BREAKING CHANGE: remove Notify out of Device DTO/Model
The current Device model/DTO contains a boolean filed `notify`.  When notify is set to true, the device service managing the device will receive a notification.  Since core-metadata will publish system event message when device is created or updated, this notify is no longer needed and should be removed.
fixes #805
> feat!: Remove Notify out of Device DTO/Model

- clients/http/command.go
- clients/http/deviceprofile.go
- clients/http/deviceservicecommand.go
- clients/http/event.go
- clients/http/reading.go
- clients/http/utils/common.go
- dtos/corecommand.go
- dtos/devicecommand.go
- dtos/deviceresource.go
- dtos/event.go
- dtos/reading.go
- dtos/requests/event_test.go
Remove the constraint of device command name and resource name, and use URL escape in client API.
Close #773
- Run core service and device service
- Verify the escape URL works, eg, escape the commandName `device-a/test:value` and put into the URL like  /api/v2/device/name/Modbus-TCP-Device/device-a%2Ftest%3Avalue
> feat: Use URL escape for device command name and resource name

- dtos/intervalaction.go
- models/intervalaction.go
Outbound HTTP requests must be authenticated if they call EdgeX services (for example, event aging).  This commit extends the model to allow users to specify the AuthMethod of outbound HTTP requests.
> feat: Specify how to authenticate outbound IntervalActions

- dtos/protocolproperties.go
- models/device.go
BREAKING CHANGE: update ProtocolProperties type from 'map[string]string' to 'map[string]any'
closes #592
> feat!: update ProtocolProperties to have typed values

- dtos/deviceprofile_test.go
- dtos/resourceproperties.go
- models/resourceproperties.go
BREAKING CHANGE: update mask,shift,base,scale,offset to numeric data type
also rename 'Others' to 'Optional' for the consistency with message broker settings.
closes #770
> feat!: update data type in ResourceProperties

- dtos/resourceproperties.go
- models/resourceproperties.go
BREAKING CHANGE: update maximum and minimum data type from string to float64
closes #816
https://github.com/edgexfoundry/edgex-docs/pull/984
> feat!: update maximum and minimum to float64 data type

- dtos/discovereddevice.go
- dtos/provisionwatcher.go
- dtos/provisionwatcher_test.go
- dtos/requests/provisionwatcher.go
- dtos/requests/provisionwatcher_test.go
- models/discovereddevice.go
- models/provisionwatcher.go
BREAKING CHANGE: add 'discoveredDevice' field which includes serviceName, profileName,adminState,autoEvents and properties for discovered device
closes #813
> feat!: add 'discoveredDevice' for discovered device fields

- dtos/reading.go
BREAKING CHNAGE: Since the string value might be empty from specified device, we need to remove SimpleReading value required validation for empty string.
Close #753
Run unit test
> feat!: Remove SimpleReading value required validation for empty string

- clients/http/command.go
- clients/http/command_test.go
- clients/http/deviceprofile.go
- clients/http/utils/common.go
- common/utils.go
- common/utils_test.go
BREAKING CHANGE: To consist with the change for MQTT topic path encoding, use PathEscape to encode the API path because the url.QueryEscape encode the empty space to plus sign, and plus sign is invalid for publishing the MQTT message.
Run core services and device service to check whether the event can publish to the message bus.
This modification is based on the issue https://github.com/edgexfoundry/device-sdk-go/issues/1433
> feat!: Using url.PathEscape for http client request path

- common/validator.go
- dtos/discovereddevice.go
- dtos/requests/provisionwatcher_test.go
Update the provisionWatcher DTO to allow empty string profile
Close #830
Run unit test
> feat: Allow Device Profile to be empty string in ProvisionWatcher

- common/constants.go
Restore core-command topic key for external MQTT configuration
> fix: Restore core-command topic key

- dtos/reading.go
- dtos/reading_test.go
fix: #858 
From the latest compose-builder run `make run no-secty ds-virtual`
Run `docker stop edgex-core-data`
From the latest edgex-go run `git clone --branch issue-858 git@github.com:FelixTing/go-mod-core-contracts.git`, add the following line to go.mod, and run core-data locally.
```
replace github.com/edgexfoundry/go-mod-core-contracts/v3 => ./go-mod-core-contracts
```
Create an event with array values
```
curl -X POST http://127.0.0.1:59880/api/v3/event/device-virtual/Random-UnsignedInteger-Device/Random-Unsig …
```
> fix: use comma without a space as separator to parse array value

- clients/http/event.go
- clients/http/event_test.go
- clients/interfaces/event.go
- clients/interfaces/mocks/EventClient.go
Closes #868 
No docs change necessary
1. Update app-functions-sdk-go with updated version of go-mod-core-contracts (using `replace`, for example)
2. From a new application service, import the new version of app-functions-sdk-go (using `replace`, for example) and use `interfaces.EventClient` the same as before. `DeleteById(ctx, id)` will be available.
N/A
> feat(EventClient): add DeleteById to interface

- dtos/address.go
- dtos/address_test.go
- models/address.go
Requires update of `edgex-go` support notifications. See https://github.com/edgexfoundry/edgex-go/issues/4747#issuecomment-1911312262
N/A
> feat: add injectEdgeXAuth boolean attribute to RESTAddress types

- clients/doc_test.go
- clients/http/authinjector_test.go
- clients/http/utils/common.go
- clients/interfaces/authinjector.go
Uses the authInjector to set the RoundTripper to use when making requests. Necessary to integrate with OpenZiti. See go-mod-bootstrapper at https://github.com/edgexfoundry/go-mod-bootstrap
- [x ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x ] I am not introducing a new dependency (add notes below if you are)
This is a sweeping change that crosses numerous repos. I don't know how to effectively answer this particular question and this one change is insufficient for testing. A larger, cross-cutting PR/effort is needed to put all the pieces together. I could use help with knowing how to satisfy this
none
> feat: add openziti to core contracts

- dtos/device.go
- dtos/requests/device_test.go
BREAKING CHANGE: Allow empty profileName in Device, and set AdminState as Locked and OperatingState as Down by default
closed #901
> feat: Allow empty profileName in Device

- common/constants.go
- dtos/deviceprofile.go
- dtos/deviceprofile_test.go
- dtos/responses/deviceprofile.go
- dtos/responses/deviceprofile_test.go
Add multiple profile basic info DTO for /api/v3/deviceprofile/basicinfo/all API
- core-data and metadata
- upload profiles
- test the API
> feat: Add multiple profile basic info DTO

- common/constants.go
Resolves edgexfoundry/edgex-go#4836.
Add the security bootstrapper key for postgres db.
> feat: Add security bootstrapper key for postgres db

- dtos/schedulejob.go
- dtos/schedulejob_test.go
- models/device.go
closes: #915
- Make AdminState as an optional field with UNLOCKED as default value
- Enhance the models and DTOs for Cron Scheduler service
> feat: Set Default Value for AdminState and Enhancements for Cron Scheduler

- dtos/requests/schedulejob.go
- dtos/requests/schedulejob_test.go
Fix missing AutoTriggerMissedRecords for patching schedule job in ReplaceScheduleJobModelFieldsWithDTO.
> fix: Fix missing AutoTriggerMissedRecords for patching schedule job

- dtos/event_test.go
- dtos/reading.go
- dtos/reading_test.go
- dtos/requests/event.go
- dtos/requests/event_test.go
Allow reading value to be null
closes: #931
Run device simple and test nil value.
> feat: Allow reading value to be null

- dtos/reading.go
- dtos/reading_test.go
- dtos/requests/event_test.go
- models/reading.go
Allow store reading value as null
Test with simple device service.
> feat: Allow store reading value as null

- dtos/requests/schedulejob.go
- dtos/requests/schedulejob_test.go
refer to https://github.com/edgexfoundry/edgex-go/issues/4925
> fix: Added validation for UpdateScheduleJobRequest

- dtos/event.go
- dtos/event_test.go
- dtos/reading.go
- dtos/reading_test.go
- dtos/requests/event_test.go
- models/reading.go
Using isNull to indicate the reading value should be nul after marshaling.
> refactor: Using isNull instead of nil reading value

- dtos/autoevent.go
- dtos/requests/device_test.go
- dtos/requests/provisionwatcher_test.go
- models/autoevent.go
The onChange flag in Device AutoEvent can prevent any non changed values sent out. The onChangeThreshold could provide the advanced feature, and the default value is 0, any changed value that exceeds (>) bounds shall be published. For example, Current_value - Current_prev > 0.01 shall be published where "Current_value" is the new value and "Current_prev" is the previously published value.
> feat: Add onChangeThreshold in Device AutoEvent

- dtos/reading.go
- dtos/requests/event_test.go
Since we accept the nil reading value, the binary reading value can be empty
fixes edgex-go#4986
Run make test.
> fix: Allow binary reading value to be empty

- clients/http/utils/common.go
- clients/http/utils/common_test.go
- clients/http/utils/request.go
- errors/types.go
Fixes #954. Add the post with headers util function for HTTP clients.
> feat: Add the post with headers util function for HTTP clients

- common/constants.go
- dtos/address.go
- dtos/requests/subscription.go
- dtos/requests/subscription_test.go
relate: https://github.com/edgexfoundry/edgex-go/issues/5007
> feat: Add MQTT and ZeroMQ channels support to support-notification

- common/validator.go
- common/validator_test.go
fixes #966
```go
type User struct {
Name  string
Roles []string `validate:"unique"`
}
type Group struct {
Users []User `validate:"unique=Name"` // only one field can be specified
}
func main() {
user := User{
Name:  "admin",
Roles: []string{"admin", "admin"},
}
err := common.Validate(user)
// User.Roles field should only contain unique elements
group := Group{
Users: []User{
{
Name: "user1",
},
{
Name: "user1",
},
},
}
err = common.Validate(group)
// Group.Users field should only contain unique elements with unique …
```
> fix: Generate proper error message for 'unique' validation tag

- clients/common.go
- clients/http/command.go
- clients/http/device.go
- clients/http/deviceprofile.go
- clients/http/deviceservice.go
- clients/http/event.go
- clients/http/notification.go
- clients/http/provisionwatcher.go
- clients/http/reading.go
- clients/http/scheduleactionrecord.go
- clients/http/schedulejob.go
- clients/http/subscription.go
relate: https://github.com/edgexfoundry/go-mod-bootstrap/issues/804
> feat: use baseUrlFunc instead baseUrl for Clients

- dtos/requests/event.go
- dtos/responses/event.go
close https://github.com/edgexfoundry/go-mod-core-contracts/issues/972
> feat: Add helper func in event DTOs

- dtos/autoevent.go
- models/autoevent.go
Add AutoEvent Retention Model and DTO for event retention enhancement
> feat: Add AutoEvent Retention Model and DTO

- errors/types.go
> feat: Add Kind() method to EdgeX error interface

- dtos/common/count.go
> fix: Add JSON Tag for Count Field in CountResponse

- clients/http/subscription_test.go
- dtos/address.go
- dtos/requests/subscription_test.go
- models/address.go
add HTTPS support to REST
Closes https://github.com/edgexfoundry/edgex-go/issues/5099
> feat: Add HTTPS support to REST

- dtos/autoevent.go
Auto event duration should allow empty because the Core Metadata will apply the default value if duration is empty.
Close #987
Test core metadata API with empty duration like below
```
curl 'http://localhost:59881/api/v3/device' \
--header 'Content-Type: application/json' \
--data '[{
"device": {
"name": "testDevice",
"adminState": "UNLOCKED",
"operatingState": "UP",
"location": {},
"serviceName": "device-virtual",
"profileName": "Random-Boolean-Device",
"autoEvents": [
{ "interval": "1s", "onChange": false, …
```
> fix: Allow Auto event duration is empty

- dtos/address.go
fixes https://github.com/edgexfoundry/go-mod-core-contracts/issues/990
The PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/986 set the scheme configurable in NewRESTAddress, but didn't consider a default value when scheme is empty string.
This commit will set http as the default value when scheme is an empty string.
> fix: NewRESTAddress use http as default scheme

- dtos/event_test.go
- dtos/reading.go
- dtos/reading_test.go
fixes https://github.com/edgexfoundry/go-mod-core-contracts/issues/989
The original implemetation uses `fmt.Sprintf("%e", value)` to convert float to string, which will be truncated and rounded at the 6th decimal point. For a float value that needs more precision (not arbitrary precision), it's better to use `strconv.FormatFloat` with prec -1 to achieve the smallest number of digits necessary such that ParseFloat will return f exactly. Moreover, as `fmt.Sprintf` is for more general purpose and `strconv.FormatFloat` is specifically for formatting a float, the `strconv.FormatFloat` has better performance than `fmt.Sprintf`.
The benchmark test shows the strconv.FormatFloat takes 955.5 ns/op and fmt.Sprintf takes 1961 ns/op.
If your build fails due to your commit message not passing the build …
> fix: parse float to string with precision to a sufficient level

- go.mod
Per https://github.com/dependabot/dependabot-core/issues/11825 and https://github.com/dependabot/dependabot-core/pull/11826 ,the dependabot has been updated to use GOTOOLCHAIN=go1.24.1 and it will add toolchain in `go mod tidy` when the go directive is specified with language version (1.N). As we don't want the toolchain to be specified with go1.24.1, change the go directive to released version (1.N.P).
> build(deps): revise go directive to 1.23.0

- clients/http/deviceprofile.go
- clients/http/deviceprofile_test.go
> fix: Initialize resourcesCache for new DeviceProfileClient
