edgexfoundry/go-mod-core-contracts

clients/metadata/provision_watcher.go, clients/metadata/provision_watcher_test.go
Implements #5 
Signed-off-by: Joan Duran <jduran@circutor.com>
=> Added provision watcher client

clients/request.go
=> 404 should be wrapped with ErrServiceClient

clients/metadata/device.go
Remove DevicesForAddressable and DevicesForAddressableByName functions from device
fix #21
=> Remove Addressable related func from Device Client

models/autoevent.go
=> Add godoc to AutoEvent and correct frequency type

README.md
=> Added initial README content.

clients/constants.go, clients/coredata/event.go, clients/metadata/device_profile.go, clients/request.go, models/profileproperty.go, models/profileproperty_test.go, models/reading.go, models/reading_test.go, models/value-descriptor_test.go
Issue #32 
This should not be the final say, but is the initial refactoring required for work to continue.
=> Added CBOR data type constant and basic framework.

models/value-descriptor.go, models/value-descriptor_test.go
=> Added missing field to ValueDescriptor.

clients/context.go, clients/coredata/event.go, clients/request.go, go.mod, models/event.go
=> Events can now be marshalled as CBOR.

models/profileproperty.go, models/profileproperty_test.go, models/propertyvalue.go, models/propertyvalue_test.go, models/reading.go, models/reading_test.go
=> Moved MediaType field from ProfileProperty to PropertyValue

models/autoevent.go
=> Correct AutoEvent Frequency godoc

clients/coredata/reading.go
=> Removed unused method.

models/action.go, models/actiontype.go, models/addressable.go, models/adminstate.go, models/callbackalert.go, models/category.go, models/channel.go, models/channel_type.go, models/command.go, models/commandresponse.go, models/describedobject.go, models/device.go, models/deviceprofile.go, models/devicereport.go, models/deviceresource.go, models/deviceservice.go, models/event.go
#31 continued
Updating the GoDoc content of the models in the contracts module in small doses. I can only take so much.
=> Updated GoDoc content on first 17 models

Makefile, clients/constants.go, clients/doc.go, clients/logger/logger.go, clients/scheduler/interval.go, clients/types/errors.go, models/channel.go
#55 
As done in other repos, ran `gofmt` on whole project and then added check to Makefile via `make test` target which will cause the build to fail if any file in the PR isn't formatted correctly.
=> Go fmt on whole project, added check to Makefile

models/commandresponse.go, models/device.go, models/deviceprofile.go, models/deviceprofile_test.go
#59 
Integration work with edgex-go is complete and pending merge of this PR.
=> Rename DeviceProfile Resources and Commands

requests/states/admin/update.go, requests/states/operating/update.go
Added required JSON unmarshallers.
=> Added JSON unmarshallers.

models/reading.go
=> BUG -- Reading Value Mis-Assigned During Unmarshal

models/deviceprofile.go
=> Set Description During DeviceProfile.Unmarshal()

models/reading.go, models/reading_test.go
=> Removing Required Device Name from Reading

clients/coredata/event.go, clients/coredata/event_test.go
=> Extend EventClient to Allow "Mark Pushed by Checksum"

go.mod
Fix #246 
Signed-off-by: tobiasmo1 <tobias.mosby@intel.com>
=> Update to production release v1.1.4 of Go Codec

models/registration.go
=> Registration.Filter Incorrect Marshaling as 'filter.go'

.gitignore, Dockerfile.build, Dockerfile.build-arm64, Jenkinsfile, Makefile
Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>
=> Add code coverage output for codecov

clients/coredata/value_descriptor.go, clients/coredata/value_descriptor_test.go
Fix #118
Add method to ValueDescriptorClient interface and implementation which
consumes the ValueDescriptor Usage API.
Add tests to cover new functionality
=> Add ValueDescriptor Usage API to client

clients/coredata/value_descriptor.go
Fix #122
Fixed issue with the generation of URL not including the names query
parameters
=> Fix ValueDescriptorClient Usage Method

clients/constants.go
#124 
Signed-off-by: Iain Anderson <iain@iotechsys.com>
=> Add constant for 'version' route

models/provisionwatcher.go, models/provisionwatcher_test.go, models/validator.go
=> Update ProvisionWatcher model as per #111

models/transmission.go, models/transmission_status.go, models/transmission_status_test.go, models/transmission_test.go
Addresses #130.
Signed-off-by: Nikolay Stanchev <nstanchev@vmware.com>
=> Transmission Add Unmarshalling Validation

clients/types/errors.go
Fix #133
Update logic using pointers rather than values when dealing with errors.
=> Standardize errors

go.mod, models/command.go, models/command_test.go
Fixes #139 
Originally tracked by edgexfoundry/edgex-go/issues/1595.
This will need a corresponding Edinburgh fix, and will require investigation to see if there are other structs where this issue exists.
=> Command is not unmarshalled correctly.

models/notifications.go, models/notifications_test.go, models/transmission_test.go
Fix #135.
Signed-off-by: Nikolay Stanchev <nstanchev@vmware.com>
=> Add Unmarshalling Validation to Notification

models/channel_type.go, models/channel_type_test.go
Fix #137.
Signed-off-by: Nikolay Stanchev <nstanchev@vmware.com>
=> Add Unmarshalling Validation to ChannelType

models/sma_operation.go
Required for https://github.com/edgexfoundry/edgex-go/issues/770.
Fixes: https://github.com/edgexfoundry/go-mod-core-contracts/issues/159
Signed-off-by: Michael W. Estrin <me@michaelestrin.com>
=> Add Parameters field to models.Operations struct

models/action.go, models/action_test.go
[This will be the first of approximately 35 pull requests addressing issue #143.](https://github.com/edgexfoundry/go-mod-core-contracts/pull/157#pullrequestreview-298097581)
=> Updated Action model to correctly marshal an empty object.

models/action_test.go, models/addressable.go, models/addressable_test.go, models/constants.go, models/describedobject_test.go, models/device_test.go, models/deviceservice_test.go, models/put_test.go, models/response_test.go
This is PR 2 of approximately 35 addressing issue #143.
=> Updated Addressable model to correctly marshal an empty object.

models/interval.go, models/interval_action.go, models/interval_action_test.go, models/interval_test.go, models/log_entry.go, models/notifications.go, models/notifications_test.go, models/notify_update.go, models/profileproperty.go, models/profileproperty_test.go
Part 5 of 6 for #143
This PR requires part 3 be completed first.
This PR includes:
interval
interval_action
log_entry
notifications
notify_update
profileproperty
=> Update models to serialize zero values as empty JSON objects, part 5

models/devicereport.go, models/devicereport_test.go, models/deviceresource.go, models/deviceresource_test.go, models/event.go, models/event_test.go, models/get.go, models/get_test.go
Part 6 of 6 for #143
This PR includes:
1. describedobject
2. devicereport
3. deviceresource
4. event
5. get
=> Update models to serialize zero values as empty JSON objects, part 6

models/sma_operation.go
This reverts commit 5aef3dc028a06392063104b197c89395c8d3b66b.
See https://github.com/edgexfoundry/edgex-go/issues/1851#issuecomment-543806893
This and https://github.com/edgexfoundry/edgex-go/pull/1960 will close edgexfoundry/edgex-go#1851
=> Revert "Add Parameters field to models.Operations struct"

clients/logger/logger.go
=> Create new LoggingClient factory that does not check logTarget.

models/propertyvalue.go
Added yaml:"mediaType,omitempty" to MediaType
close #187
=> bug(modules): Add missing yaml attribute to PropertyValue.MediaType

clients/command/client.go, clients/coredata/event.go, clients/coredata/event_test.go, clients/coredata/reading.go, clients/coredata/reading_test.go, clients/coredata/value_descriptor.go, clients/coredata/value_descriptor_test.go, clients/general/client.go, clients/notifications/client.go, clients/scheduler/interval.go, clients/scheduler/interval_action.go, clients/urlclient/factory_test.go, clients/urlclient/local_test.go, clients/urlclient/registry_test.go
This PR is the seventh part of several working on #196.
This PR refactors all of scheduler's client methods.
=> Refactor Client Code, part 7/7: scheduler

Dockerfile.build, Jenkinsfile, go.mod
=> build: Update relevant files in go-mod-core-contracts for Go 1.13.

clients/constants.go, clients/general/client.go
Fixes: https://github.com/edgexfoundry/go-mod-core-contracts/issues/216
Signed-off-by: Michael W. Estrin <me@michaelestrin.com>
Issue Number: https://github.com/edgexfoundry/go-mod-core-contracts/issues/216
=> Add Health Endpoint to General Client

clients/constants.go, clients/general/client.go
Fixes: https://github.com/edgexfoundry/go-mod-core-contracts/issues/218
Signed-off-by: Michael W. Estrin <me@michaelestrin.com>
Issue Number: https://github.com/edgexfoundry/go-mod-core-contracts/issues/218
=> Revert "Add Health Endpoint to General Client (#217)"

clients/urlclient/retry/client.go, clients/urlclient/retry/client_test.go
=> Fixed bug in urlClient retry algorithm causing positive condition to never occur

clients/coredata/event_test.go, go.mod, models/event.go, models/event_test.go, models/reading_test.go
Fixes #232 
Change our CBOR library for security reasons. See https://github.com/edgexfoundry/edgex-go/issues/2439 for details.
=> Change CBOR library to fxamacker/cbor

clients/constants.go
SMA agent operation api 404 not found
Issue Number: #256 
SMA agent operation api is called successfully.
No
No
No
=> fixed: #256 SMA agent operation api 404 not found

v2/models/reading.go
Make Reading interface can access BaseReading.
Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/261
Signed-off-by: Lindsey Cheng <beckysocute@gmail.com>
Issue Number: #261
=> Refactor: Improve Reading field accessibility

v2/dtos/autoevent.go, v2/dtos/command.go, v2/dtos/device.go, v2/dtos/deviceprofile.go, v2/dtos/deviceresource.go, v2/dtos/deviceservice.go, v2/dtos/profileresource.go, v2/dtos/protocolproperties.go, v2/dtos/requests/device.go, v2/dtos/requests/device_test.go, v2/dtos/requests/deviceprofile.go, v2/dtos/requests/deviceprofile_test.go, v2/dtos/requests/deviceservice.go, v2/dtos/requests/deviceservice_test.go, v2/models/command.go
Fix #258 
Issue Number: #258 
Create device and deviceService, device profile updating DTOs for v2 API.
=> feat(metadata): Create metadata updating V2 DTOs

v2/dtos/device.go, v2/dtos/deviceprofile.go, v2/dtos/deviceservice.go
Fix #266
Issue Number: #266 
Add apiVersion to device and deviceProfile, deviceService DTO
=> feat(metadata): Add Versionable to V2 Response DTO

go.mod, models/event.go, models/event_test.go, v2/dtos/event.go, v2/dtos/event_test.go, v2/dtos/requests/event.go, v2/dtos/requests/event_test.go, v2/models/event.go
Issue Number:  #270
`Tags` field is on V1 Event model and V2 Event DTO and model
no
=> feat: Add `Tags` field to V1 Event model and V2 Event DTO and model

clients/metadata/device_service.go
Signed-off-by: Diana Atanasova <dianaa@vmware.com>
Issue Number:
https://github.com/edgexfoundry/go-mod-core-contracts/issues/274
=> Add Update method in DeviceServiceClient

errors/types.go, errors/types_test.go, go.mod, v2/dtos/common/base.go, v2/dtos/common/base_test.go, v2/dtos/reading.go, v2/dtos/requests/device.go, v2/dtos/requests/deviceprofile.go, v2/dtos/requests/deviceservice.go, v2/dtos/requests/event.go, v2/dtos/responses/device.go, v2/dtos/responses/device_test.go, v2/dtos/responses/deviceprofile.go, v2/dtos/responses/deviceprofile_test.go, v2/dtos/responses/deviceservice.go, v2/dtos/responses/deviceservice_test.go, v2/dtos/responses/event.go, v2/dtos/responses/event_test.go, v2/dtos/responses/reading.go, v2/dtos/responses/reading_test.go, v2/errors.go, v2/errors_test.go, v2/validator.go
Issue Number:  Fix #278 
Create new error type to be used by EdgeX services for more consistent error handling.
Leverage the new error wrapping and unwrapping features available in Go 1.13.
Provide more debug information about the caller.
Only for V2 API
=> feat: new error mechanism for V2 API

v2/constants.go, v2/dtos/deviceprofile.go, v2/dtos/requests/deviceprofile.go
Fix #292 
Issue Number: #292
- Add API route path for issue edgexfoundry/edgex-go#2697
- Refactor DTO func
=> feat(metadata): Add API route path for metadata V2 API

errors/types.go
=> feat: add new error types for device SDK v2 API

v2/constants.go, v2/dtos/command.go, v2/dtos/const_test.go, v2/dtos/deviceprofile.go, v2/dtos/deviceprofile_test.go, v2/dtos/deviceresource.go, v2/dtos/profileresource.go, v2/dtos/propertyvalue.go, v2/dtos/requests/deviceprofile.go, v2/dtos/resourceoperation.go
Fix #310
Issue Number: #310
Add function to transform device profile model to DTO
=> feat(metadata): Add func to transform the deviceProfile model to DTO

v2/dtos/autoevent.go, v2/dtos/device.go, v2/dtos/deviceprofile.go, v2/dtos/deviceservice.go, v2/dtos/protocolproperties.go, v2/dtos/requests/device.go, v2/dtos/requests/deviceservice.go
Fix #312
DTO model transform func lack of Id field
Issue Number: #312
Add Id field to deviceProfile, device, deviceService DTO Model transform func
=> fix(metadata): Add Id field to DTO Model transform func

v2/constants.go
Fix #322
Issue Number: #322 
Add following route path:
- /deviceprofile/all
- /deviceprofile/id/{id}
- /deviceprofile/manufacturer/{manufacturer}
- /deviceprofile/model/{model}
- /deviceprofile/manufacturer/{manufacturer}/model/{model}
=> feat(metadata): Add API route path for device profile

v2/constants.go
Add following route path:
- /deviceservice/all
- /deviceservice/id/{id}
- /deviceservice/name/{name}
Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/324
https://github.com/edgexfoundry/go-mod-core-contracts/issues/324
Add following route path:
- /deviceservice/all
- /deviceservice/id/{id}
- /deviceservice/name/{name}
Are there any specific instructions or things that should be known prior to …
=> feat(metadata): Add API route path for device service

v2/dtos/common/base.go, v2/dtos/common/base_test.go, v2/dtos/event.go, v2/dtos/event_test.go, v2/dtos/requests/device_test.go, v2/dtos/requests/deviceprofile_test.go, v2/dtos/requests/deviceservice_test.go, v2/dtos/requests/event.go, v2/dtos/requests/event_test.go, v2/dtos/responses/device_test.go, v2/dtos/responses/deviceprofile_test.go, v2/dtos/responses/deviceservice_test.go, v2/dtos/responses/event.go, v2/dtos/responses/event_test.go, v2/dtos/responses/reading_test.go, v2/models/device.go
Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/328
Replace RequestID with RequestId and Event.ID with Event.Id to make the
term consistent.
=> fix: replace ID to Id in V2

v2/constants.go
V2 API implementation needs the following constants:
- deviceName
- created
- modified
- valueType
- serviceName
- profileName
Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/347
=> feat: Add more constants core-data and metadatai

v2/constants.go
Fix #350
Add the following route paths:
- /device/all
- /device/id/{id}
- /device/name/{name}
- /device/check/id/{id}
- /device/check/name/{name}
- /device/profile/id/{id}
- /device/profile/name/{name}
- /device/service/id/{id}
- /device/service/name/{name}
=> feat(metadata): Add API route path for device

v2/constants.go
Fix #350
For creating the DB query condition, add label constant for Redis key
=> feat(metadata): Add label constant for redis key

clients/constants.go
N/A
#285 
Add constant for Vault access
N/A
N/A
=> feat: Add constant for Redis bootstrap

clients/constants.go
No constant for ContentTypeXML
#352  
Constant exists --> ContentTypeXML = "application/xml"
No
=> feat: Add ContentTypeXML to clients.constants

v2/constants.go
Fix #358
Modify event and reading API route path:
- /event/device/{deviceName}/all => /event/device/name/{name}
- /reading/device/{deviceName}/all => /reading/device/name/{name}
=> refactor(data): Modify event and reading V2 API route path

v2/constants.go
Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/360
Rename some API routes constant to be consistent with edgex-go func name
=> refactor: Rename constant to match edgex-go funce

clients/logger/logger.go
Bogus error log message logged when logging configured for STDOUT
No error message logged for this logging configuration.
Need for Security Utility to run in silent mode
=> fix: Remove error log message when logging set to STDOUT

v2/dtos/reading.go, v2/dtos/reading_test.go, v2/dtos/requests/event_test.go, v2/models/reading.go
fix #370 
Per decision made in Ireland planning meeting, we shall update Reading
DTO/Models with following changes:
1. change field "name" to "resourceName"
2. add new field "profileName"
=> fix: Modify the fields in Reading DTO and Model

v2/dtos/propertyvalue.go, v2/dtos/reading.go, v2/dtos/requests/event_test.go, v2/models/propertyvalue.go, v2/models/reading.go
Fix #372
All the floatEncoding fields should be removed
=> refactor(v2): Remove base64 encoding for float value

v2/dtos/event.go, v2/dtos/event_test.go, v2/dtos/requests/event.go, v2/dtos/requests/event_test.go, v2/models/event.go
Per decision made in Ireland planning meeting, V2 Event DTO/Model should contain a profileName field.
#373 
Add new field `ProfileName` into Event DTO and model.
fix #373
=> feat(data): Add profileName to Event DTO and Model

v2/dtos/reading.go, v2/models/reading.go
Per decision made in DeviceService WG meeting, Labels shoudl be moved out of V2 Reading DTO/Models
fix #381
=> feat(data): Remove Labels out of V2 Reading DTO/Model

v2/clients/http/data/sample-profile.yaml, v2/clients/http/deviceprofile.go, v2/clients/http/deviceprofile_test.go, v2/clients/http/utils/common.go, v2/clients/http/utils/request.go, v2/clients/interfaces/deviceprofile.go
Fix #390
Add yaml request helper method and V2 client for uploading device profile in YAML file
=> feat(meta): Add V2 client for uploading device profile in YAML file

clients/logger/logger.go, clients/logger/logger_test.go
Fix #294, fix #295 
- Add support to get current log level 
- Add formatted alternatives to log functions
=> feat: Enhance the LoggingClient function

v2/clients/http/common_test.go, v2/clients/http/deviceprofile.go, v2/clients/http/deviceprofile_test.go, v2/clients/http/utils/common.go, v2/clients/http/utils/request.go, v2/clients/interfaces/deviceprofile.go
Fix #388
Add Delete helper method and V2 client for deleting device profile
=> feat(meta): Add V2 client for deleting device profile

v2/dtos/deviceprofile.go, v2/dtos/deviceprofile_test.go, v2/dtos/requests/deviceprofile.go
Fix #395
Implement the following validation logic:
- deviceResources should not duplicated
- deviceComands should not duplicated
- coreCommands should not duplicated
- coreCommands should match the one of deviceResources and deviceComands
- deviceResources referenced in deviceCommands must exist
=> feat(meta): Implement validation logic for device profile DTO

v2/constants.go
fix #400
Per latest swagger file for core-data, several V2 API path constants needs 
to be changed:
- /event/count/device/{deviceName} -> /event/count/device/name/{name}
- /reading/type/{type} -> /reading/resourceName/{resourceName}
to be added:
- /reading/count/device/name/{name}
to be removed:
- /reading/id/{id}
=> feat(data): Update core-data V2 API path constants

v2/constants.go, v2/dtos/propertyvalue.go, v2/dtos/reading.go, v2/dtos/requests/deviceprofile.go, v2/dtos/requests/deviceprofile_test.go, v2/dtos/requests/event.go, v2/dtos/requests/event_test.go, v2/dtos/valuetype.go, v2/utils.go, v2/validator.go
Fix #383
Add valueType validation and normalization for reading, device profile
=> feat: Make valueType case insensitive and covert to camelcase internally

clients/logger/logger.go, clients/logger/mock-logger.go, v2/clients/http/device.go, v2/clients/http/deviceprofile.go, v2/clients/http/deviceservicecallback.go, v2/clients/http/deviceservicecallback_test.go, v2/clients/http/utils/common.go, v2/clients/http/utils/request.go, v2/clients/interfaces/deviceservicecallback.go, v2/constants.go
Fix #404
implement callback clients:
- Post /callback/device
- Put /callback/device
- Delete /callback/device/id/{id}
- [x ] No
=> feat: Add device service callback client for device

v2/dtos/common/secrets.go, v2/dtos/common/secrets_test.go
No commonly available SecretsRequest DTO
SecretsRequest DTO added (taken from App SDK)
=> feat: Add SecretsRequest DTO

v2/dtos/provisionwatcher.go, v2/dtos/requests/provisionwatcher.go, v2/dtos/requests/provisionwatcher_test.go, v2/dtos/responses/provisionwatcher.go, v2/dtos/responses/provisionwatcher_test.go, v2/models/provisionwatcher.go
=> feat(meta): create ProvisionWatcher Model and DTO

v2/constants.go
The current V2 API of CoreData use POST /event to add event.
fix #408 
Change the path from /event to /event/{profileName}/{deviceName} per https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/013-Device-Service-Events-Message-Bus.md
=> feat(data): Update V2 API AddEvent path

v2/constants.go
=> feat(meta): add v2 ProvisionWatcher route

v2/clients/http/reading.go, v2/clients/http/reading_test.go, v2/clients/interfaces/reading.go
Add V2 ReadingClient for interactions with V2 Reading endpoint on the Core Data Service.
- (GET) /reading/all
- (GET) /reading/count
- (GET) /reading/count/device/name/{name}
- (GET) /reading/device/name/{name}
- (GET) /reading/resourceName/{resourceName}
- (GET) /reading/start/{start}/end/{end}
=> feat(meta): Add ReadingClient

v2/dtos/common/secret.go, v2/dtos/common/secret_test.go
Naming was inconsistent with functionality and our definition of a Secret
Naming better matches functionality and our definition of a Secret
=> refactor: Change from plural Secrets to Secret and SecretData

v2/constants.go
fix #459 
Per discussion from @jpwhitemn, @lenny-intel, and @cloudxxx8, Core Command V2 API GET/PUT /device/name/{deviceName}/command/{commandName} should be changed to the same path used by device-service-sdk, which is GET/PUT /device/name/{name}/{command}
=> feat(v2 command): Update the API path to /device/name/{name}/{command}

v2/dtos/device.go, v2/dtos/deviceservice.go, v2/dtos/provisionwatcher.go
Close #465
Create transform func to convert the following Models to UpdateDTOs:
- DeviceService
- Device
- ProvisionWatcher
=> feat(V2): Create transform func to convert Model to UpdateDTO

v2/constants.go, v2/dtos/autoevent.go, v2/dtos/interval.go, v2/dtos/requests/const_test.go, v2/dtos/requests/interval.go, v2/dtos/requests/interval_test.go, v2/dtos/responses/interval.go, v2/dtos/responses/interval_test.go, v2/models/interval.go, v2/validator.go
Close #426
Create Interval DTO and Model for scheduler V2 API
- I remove the Cron field from Interval because it does nothing in the scheduler service, we can add it back if we really need it.
- Reuse the validation tag to verify the Frequency field
=> feat(scheduler): Create Interval DTO and Model

errors/types.go
Close #469
Create a new ErrKind KindStatusConflict for Delete API according to return 409 Http status code
=> feat(v2): Create new ErrKind for Delete API to return 409

v2/dtos/provisionwatcher.go
=> fix(v2): correct ProvisionWatcher dto json tag

v2/constants.go, v2/dtos/requests/subscription.go, v2/dtos/requests/subscription_test.go, v2/dtos/responses/subscription.go, v2/dtos/responses/subscription_test.go, v2/dtos/subscription.go, v2/models/category.go, v2/models/channeltype.go, v2/models/subscription.go
Create Subscription DTO and Model for Notifications V2 API
Close #431 
=> feat(notifications): Create Subscription DTO and Model

v2/dtos/device.go, v2/dtos/requests/device.go, v2/dtos/requests/device_test.go
Add factory methods for AddDeviceRequest and UpdateDeviceRequest DTO
=> feat(V2): Add factory methods for DeviceRequest DTO

v2/dtos/deviceservice.go, v2/dtos/requests/deviceservice.go, v2/dtos/requests/deviceservice_test.go
Add factory methods for AddDeviceServiceRequest and UpdateDeviceServiceRequest DTO
=> feat(V2): Add factory methods for DeviceServiceRequest DTO

v2/dtos/command.go, v2/dtos/corecommand.go, v2/dtos/deviceprofile_test.go, v2/dtos/requests/deviceprofile_test.go, v2/dtos/responses/corecommand.go, v2/dtos/responses/corecommand_test.go, v2/models/command.go
Close #487
Modified all the wording in Device Profile, including client, model, and dto.
=> refactor(meta): Rename Put Command to Set Command

v2/dtos/interval.go, v2/dtos/requests/interval.go, v2/dtos/requests/interval_test.go, v2/dtos/requests/provisionwatcher.go, v2/dtos/requests/subscription.go
fix #450 
fix #471
Add factory methods for Interval, provisionWatcher and subscription request DTO
=> feat(V2): Add factory methods for Request DTO

v2/dtos/subscription.go
- Currently, the validation tag `required_without` can not work correctly with `uuid`, so use the customized tag `edgex-dto-uuid` instead.
- With the `required_without` tag, the `Id` field under validation must be present and not empty only when the `Name` field is not present, and vice versa. So the `omitempty` tag must be removed.
Close #497
=> fix(v2): Correct UpdateSubscription DTO validation tags

v2/dtos/command.go, v2/dtos/corecommand.go, v2/dtos/device.go, v2/dtos/deviceCommand.go, v2/dtos/deviceresource.go, v2/dtos/event.go, v2/dtos/interval.go, v2/dtos/reading.go, v2/dtos/resourceoperation.go, v2/dtos/subscription.go
Close #504
- JSON add the missing `omitempty` tag
- Validate remove the redundant `omitempty` tag
=> feat(V2): Enhance the DTO's Json and Validate annotation

v2/constants.go, v2/dtos/intervalaction.go, v2/dtos/requests/const_test.go, v2/dtos/requests/intervalaction.go, v2/dtos/requests/intervalaction_test.go, v2/dtos/responses/intervalaction.go, v2/dtos/responses/intervalaction_test.go, v2/models/intervalaction.go
Close #517
Create IntervalAction DTO and Model for scheduler V2 API
=> feat(scheduler): Create V2 IntervalAction DTO and Model

v2/models/propertyvalue.go
Close #511
Per Core WG review of 2/18/21, remove the encoding constants.
=> refactor(v2): Remove encoding constants

v2/clients/http/event.go, v2/constants.go, v2/dtos/const_test.go, v2/dtos/event.go, v2/dtos/event_test.go, v2/dtos/requests/const_test.go, v2/dtos/requests/event.go, v2/dtos/requests/event_test.go, v2/models/event.go
- update Add Event REST path and event client
- add SourceName to Event model and related DTOs, factory method
=> feat: update Add Event route to include SourceName

v2/dtos/autoevent.go, v2/dtos/requests/device_test.go, v2/dtos/requests/provisionwatcher_test.go, v2/models/autoevent.go
=> feat: rename Resource to SourceName in AutoEvent model

v2/dtos/requests/event.go, v2/dtos/requests/event_test.go
fix #526 
Per review comment from https://github.com/edgexfoundry/edgex-go/pull/3202/files#r583905762, AddEventRequest DTO shall implement UnmarshalCBOR just like it does for JSON.
=> feat(data): Implement UnmarshalCBOR for AddEventRequest DTO

v2/dtos/device.go, v2/dtos/device_test.go, v2/dtos/deviceservice.go, v2/dtos/deviceservice_test.go, v2/dtos/event_test.go, v2/dtos/interval.go, v2/dtos/intervalaction.go, v2/dtos/provisionwatcher.go, v2/dtos/provisionwatcher_test.go, v2/dtos/reading.go, v2/dtos/reading_test.go, v2/dtos/requests/device.go, v2/dtos/requests/device_test.go, v2/dtos/requests/deviceservice.go, v2/dtos/requests/deviceservice_test.go, v2/dtos/requests/interval.go, v2/dtos/requests/interval_test.go, v2/dtos/requests/intervalaction.go, v2/dtos/requests/intervalaction_test.go, v2/dtos/requests/provisionwatcher.go, v2/dtos/requests/provisionwatcher_test.go, v2/dtos/requests/subscription.go, v2/dtos/requests/subscription_test.go, v2/dtos/subscription.go
Close #537
Remove ApiVersion from update DTOs
=> refactor: Remove ApiVersion from update DTOs

v2/dtos/deviceprofile.go, v2/dtos/deviceprofile_test.go, v2/dtos/requests/deviceprofile.go
fix #547
Modify the profile validation to verify both YAML and JSON format
=> fix: Modify the profile validation to verify both YAML and JSON format

v2/clients/http/device.go, v2/clients/http/deviceprofile.go, v2/clients/http/deviceservice.go, v2/clients/http/deviceservicecallback.go, v2/clients/http/event.go, v2/clients/http/provisionwatcher.go, v2/clients/http/utils/common.go, v2/clients/http/utils/request.go, v2/constants.go
=> feat: add CBOR support in EventClient for binary reading

v2/dtos/address.go, v2/dtos/address_test.go, v2/models/address.go
Signed-off-by: Felix Ting <felix@iotechsys.com>
EmailAddress model is missing.
Created EmailAddress model.
Close #551
=> fix(notifications): Create EmailAddress model

v2/constants.go
Close #563
Since we remove the created field and use origin as query parameter, the API requires the Origin constant to modify the implementation
=> feat: Add Origin constant for event and reading V2 API

v2/constants.go, v2/dtos/address.go, v2/dtos/address_test.go, v2/models/address.go
Close #576
- Rename QueryParameters to RequestBody
- Add interval constant for the DB layer implementation
=> feat(scheduler): Rename Address field and add interval constant

v2/dtos/device.go, v2/dtos/deviceservice.go, v2/dtos/interval.go, v2/dtos/provisionwatcher.go, v2/dtos/requests/deviceservice.go
Fix #581
Add the missing Description filed and omitempty tag
=> fix: Add missing UpdateDeviceService DTO filed and omitempty tag

v2/clients/http/const_test.go, v2/clients/http/interval.go, v2/clients/http/interval_test.go, v2/clients/http/intervalaction.go, v2/clients/http/intervalaction_test.go, v2/clients/interfaces/interval.go, v2/clients/interfaces/intervalaction.go, v2/dtos/interval.go, v2/dtos/intervalaction.go
Close #572
Add V2 Client:
- POST/PATCH /interval
- GET/DELETE /interval/name/{name}
- GET /interval/all
- POST/PATCH /intervalAction
- GET/DELETE /intervalAction/name/{name}
- GET /intervalAction/all
=> feat(scheduler): implement Interval and IntervalAction Client

clients/constants.go, v2/dtos/address.go, v2/dtos/address_test.go, v2/models/address.go
Close #583
- Add content length constant
- Add contentType field to Address to reuse for REST, MQTT and Email address type
=> feat: Add contentType field to Address

v2/constants.go, v2/dtos/responses/deviceresource.go, v2/dtos/responses/deviceresource_test.go
Close #586
- Add DeviceResourceResponse DTO
- Add /deviceresource/profile/{profileName}/resource/{resourceName} API route
=> feat: Add DeviceResourceResponse DTO and API route

v2/clients/http/deviceprofile.go, v2/clients/http/deviceprofile_test.go, v2/clients/interfaces/deviceprofile.go
implement Device Resource Client according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.x#/default/get_deviceresource_profile__profileName__resource__resourceName_
=> feat(meta): implement Device Resource Client

v2/dtos/deviceprofile_test.go, v2/dtos/deviceresource.go, v2/dtos/requests/deviceprofile_test.go, v2/models/deviceresource.go
`DeviceResource.Attributes` will be `map[string]interface{}` type
=> feat: update DeviceResource.Attributes type

v2/dtos/responses/event.go
=> feat: add Encode method for EventResponse

v2/constants.go, v2/dtos/address.go, v2/dtos/address_test.go, v2/dtos/intervalaction.go, v2/dtos/requests/intervalaction.go, v2/dtos/requests/intervalaction_test.go, v2/dtos/requests/subscription.go, v2/dtos/requests/subscription_test.go, v2/dtos/subscription.go, v2/dtos/transmission.go, v2/models/address.go, v2/models/consts.go, v2/models/intervalaction.go, v2/models/subscription.go, v2/models/transmission.go
Close #601
- Add adminState to Subscription and IntervalAction
- Add escalated notification const
- Add JSON unmarshal to cast the address for Transmission
=> feat(notifications): Add required const and field for sending service

Dockerfile.build, README.md, go.mod
update go.mod, Dockerfile.build, README.md
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
upgrade to Go 1.16
=> build: upgrade Go lang to 1.16

v2/dtos/common/metrics.go, v2/dtos/common/metrics_test.go
update the map value to interface to allow custom
executor use it own metrics struct.
related to https://github.com/edgexfoundry/edgex-go/issues/3454
response if MetricsMechanism is `executor`:
```
{
apiVersion: "v2",
statusCode: 200,
metrics: {
edgex-core-data: {
Success: true,
executor: "docker",
operation: "metrics",
result: {
cpuUsedPercent: 0.07,
memoryUsed: 8642363,
raw: {
block_io: "135kB / 0B",
cpu_perc: "0.07%",
mem_perc: "0.41%",
mem_usage: "8.242MiB / 1.94GiB", …
```
=> feat: update MulitMetricsResponse field type

v2/dtos/autoevent.go, v2/dtos/interval.go, v2/dtos/requests/const_test.go, v2/dtos/requests/device_test.go, v2/dtos/requests/interval.go, v2/dtos/requests/interval_test.go, v2/dtos/requests/provisionwatcher_test.go, v2/dtos/subscription.go, v2/models/autoevent.go, v2/models/interval.go, v2/validator.go
=> refactor: rename Frequency to Interval

v2/constants.go
pre-requisite of https://github.com/edgexfoundry/edgex-go/pull/3467
=> feat: add constants used by sma v2 API

v2/dtos/transmission.go, v2/models/consts.go, v2/models/transmission.go
Close #617
- Add RESENDING const to transmission
- Only use the created field in transmission
=> feat: Add const and modify field for transmission V2 API

v2/constants.go
Close #619
Remove the redundant slash from the Transmission API route constant.
=> feat: Fix the wrong Transmission V2 API route

v2/constants.go, v2/dtos/requests/const_test.go, v2/dtos/requests/operation.go, v2/dtos/requests/operation_test.go
pre-requisite of https://github.com/edgexfoundry/edgex-go/issues/3496
example request body of sma `/operation` API endpoint:
```
[
{
"apiVersion": "v2",
"requestId": "2f6fe5e2-dd93-478c-a2ba-21642e42a5f5",
"serviceName": "edgex-core-data",
"action": "stop"
},
{
"apiVersion": "v2",
"requestId": "998d70a3-7245-4735-b308-ebb9f448fb38",
"serviceName": "edgex-core-command",
"action": "restart"
}
]
```
Are there any specific instructions or things that should be known prior to …
=> feat: add OperationRequest dto for SMA

dtos/deviceprofile.go
Fix the error message type from profile validation function
=> fix: Fix error message typo

CHANGELOG.md
**N/A for change log**
**N/A for change log**
=> docs: Update change-log for 2.1.0

common/constants.go
Closes: #701
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>
- [x ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x ] I am not introducing a new dependency (add notes below if you are)
=> feat(security): Add a new constant for security-spiffe-token-provider

common/constants.go
new routes
- ApiDeviceProfileBasicInfoRoute
- ApiDeviceCommandRoute
=> feat: Add new routes for device profile changes

common/constants.go, dtos/devicecommand.go, dtos/deviceprofile.go, dtos/requests/deviceprofile_test.go, dtos/resourceproperties.go
Update the ReadWrite validation to include 'WR' value.
Fix #707 
Signed-off-by: Lindsey Cheng <beckysocute@gmail.com>
=> fix: Update the ReadWrite validation to include WR

dtos/deviceprofile.go
close #717
1. build and run metadata from this branch
2. POST /deviceprofile/uploadfile
=> fix: Add yaml:inline to DeviceProfile DTO DeviceProfileBasicInfo

dtos/const_test.go, dtos/reading.go, dtos/reading_test.go, models/reading.go
close #720
- [] I have added unit tests for the new feature or bug fix (if not, why?) update existing unit tests
- [] I have fully tested (add details below) this the new feature or bug fix (if not, why?)update DTO and model
=> feat: Add Units property to reading DTO and model

clients/http/deviceprofile.go, clients/http/deviceprofile_test.go, clients/interfaces/deviceprofile.go, clients/interfaces/mocks/DeviceProfileClient.go
=> feat: Add new device profile API clients

CHANGELOG.md
=> build: Update change log for V2.2.0

dtos/metric.go, dtos/reading.go
close #728
1. Build core-data from this branch and run with other edgex services
2. Generate a Float32Array reading and verify the response
=> refactor: Improve string concatenate logic by string builder

common/dummy_validator.go, common/validator.go
1. replace go-mod-core-contracts with this branch
2. update go build tags to include `no_dto_validator`
3. memory footprint reduce ~2MB
=> build: add go build tag to exclude DTO validator

common/constants.go, dtos/systemevent.go, dtos/systemevent_test.go
closes #751
Implements DTO portion of [ADR](https://docs.edgexfoundry.org/2.3/design/adr/0024-system-events/)
**Will be part of Core Meta documentation of Device System Events**
=> feat: Add new SystemEvent DTO

dtos/device.go, dtos/deviceservice.go, models/device.go, models/deviceservice.go
=> docs: Add deprecated annotation to lastConnected and lastReported

common/constants.go, dtos/responses/uom.go, dtos/responses/uom_test.go
https://github.com/edgexfoundry/edgex-go/pull/4127
=> feat: add UoM api route and response

clients/http/utils/common.go
=> fix: keep the existing baseUrl path in helper function

common/constants.go
=> feat: Add service key for new core-common-config-bootstrapper service

common/constants.go, dtos/systemevent_test.go
=> feat: Add new system event type constants and rename action constants

dtos/reading.go, dtos/reading_test.go
=> feat: Add UnmarshalObjectValue helper function to Reading DTO

common/constants.go
=> fix: Correct name of topic constant for subscribing to system events

clients/http/common_test.go, dtos/common/secret.go, dtos/common/secret_test.go
closes: #768
Signed-off-by: Marc-Philippe Fuller <marc-philippe.fuller@intel.com>
`make test`
=> refactor(mod): Refactor Secret DTO to rename Path property to SecretName

clients/http/event.go, clients/http/event_test.go, clients/interfaces/event.go, common/constants.go
BREAKING CHANGE: update EventClient 'Add' method signature
closes #799
=> feat!: add device service name in Add Event API endpoint

Makefile, clients/doc.go, clients/http/utils/common.go, go.mod
<link to docs PR> 
make sure v1.51.2 of linter is installed
make test
verify no format or linter issues
=> build: Update to Go 1.20 and linter v1.51.2

common/constants.go
related to edgexfoundry/edgex-go#4279
=> feat: add 'ds-regexcmd' query parameter

dtos/autoevent.go, dtos/device.go, dtos/provisionwatcher.go
to support the standard YAML format for all config/definition files
related to edgexfoundry/device-sdk-go#1380, edgexfoundry/device-sdk-go#1381
=> feat: add YAML tag for Device and ProvisionWatcher

dtos/resourceproperties.go, models/resourceproperties.go
BREAKING CHANGE:
- update mask,shift,base,scale,offset to pointer
- update maximum and minimum data type from string to float64 pointer
related to #821
https://github.com/edgexfoundry/edgex-docs/pull/989
=> fix!: Modify the numeric data type in Value Properties to pointer

common/utils.go, common/utils_test.go
=> feat: add URLEncode helper function

clients/http/utils/common.go, clients/http/utils/common_test.go
Combine baseUrl and request path properly for creating the http request.
Close #837
Run unit test
=> feat: Combine baseUrl and path properly

common/echo_api_constants.go
Closes #845. Add new API route constants with path params for Echo.
=> feat: Add new API route constants for Echo

common/echo_api_constants.go
Add todo comment for the new Echo API route consts.
=> fix: Add todo comment for the new Echo API const

Makefile, common/constants.go, go.mod
=> build: Upgrade to go 1.21 and linter 1.54.2

common/constants.go
=> fix: Restore previouly removed constants that are still used.

clients/http/kvs.go, clients/http/kvs_test.go, clients/http/registry.go, clients/http/registry_test.go, clients/http/utils/request.go, clients/interfaces/kvs.go, clients/interfaces/registry.go, common/constants.go, common/echo_api_constants.go, dtos/registration.go, dtos/registration_test.go, dtos/requests/kvs.go, dtos/requests/kvs_test.go, dtos/requests/registration.go, dtos/requests/registration_test.go, dtos/responses/kvs.go, dtos/responses/kvs_test.go, dtos/responses/registration.go, dtos/responses/registration_test.go, models/consts.go, models/kvs.go, models/registration.go
=> feat: Add the http clients/dtos of KVS and registry for Keeper

clients/http/kvs.go, clients/http/kvs_test.go, clients/interfaces/kvs.go
closes #885
This is not a breaking change as Core Keeper hasn't been released yet.
=> feat: Add 'flatten' parameter to UpdateValuesByKey

dtos/device.go, dtos/requests/device_test.go
=> feat: Remove the restrition of Device Protocols

common/constants.go, common/utils.go, common/validator.go, dtos/reading.go, dtos/reading_test.go, models/reading.go
Close https://github.com/edgexfoundry/go-mod-core-contracts/issues/898
=> feat: Add ObjectArray valueType support

dtos/requests/schedulejob_test.go, dtos/schedulejob.go
- Fix the wrong json name for IntervalScheduleDef
- Add missing field "Method" for RESTAction
=> fix: Fix DTOs for Cron Scheduler

models/schedulejob.go
=> fix: Add missing field "Method" to RESTAction model

dtos/schedulejob.go, dtos/schedulejob_test.go
=> fix: Add missing field "Method" to model and DTO transform functions

models/schedulejob.go
=> feat: Make the unmarshalScheduleAction Function Public

dtos/scheduleactionrecord.go, dtos/scheduleactionrecord_test.go, dtos/schedulejob.go, dtos/schedulejob_test.go, models/const_test.go, models/schedulejob.go, models/schedulejob_test.go
=> feat: Add Start, End Timestamp for ScheduleJob and ID for ScheduleAction

clients/http/schedulejob.go, clients/http/schedulejob_test.go, clients/interfaces/mocks/ScheduleJobClient.go, clients/interfaces/schedulejob.go
Docs will be updated while implementing this API in edgex-go.
=> feat: Support query schedule jobs with labels

models/schedulejob.go, models/schedulejob_test.go
Enhance WithEmptyPayloadAndId method to avoid storing duplicate data in DB.
=> feat: Enhance WithEmptyPayloadAndId method

models/schedulejob.go, models/schedulejob_test.go
Enhance WithId Method of ScheduleAction to allow passing custom ID in it.
=> feat: Enhance WithId Method of ScheduleAction

dtos/schedulejob.go, dtos/schedulejob_test.go, models/schedulejob.go, models/schedulejob_test.go
Related to https://github.com/edgexfoundry/edgex-go/issues/4897
Doc and API doc will be updated in
- https://github.com/edgexfoundry/edgex-docs/pull/1373
- https://github.com/edgexfoundry/edgex-go/pull/4898
=> feat: Add AutoTriggerMissedRecords to ScheduleJob

dtos/reading.go, dtos/requests/event.go, dtos/requests/event_test.go
close https://github.com/edgexfoundry/edgex-go/issues/4964
=> fix: fix binary reading validation

dtos/event_test.go, dtos/reading.go
Since BinaryReading is decoded by CBOR, we should add UnmarshalCBOR for checking the nil value
Run make test.
=> feat: Add CBOR encode and decode for BaseReading

dtos/reading.go, dtos/reading_test.go
fix inconsistent reading DTO JSON marshal and unmarshal
fixes: https://github.com/edgexfoundry/edgex-go/issues/4964
Run `make test`.
=> fix: fix inconsistent reading DTO JSON marshal and unmarshal

common/constants.go, dtos/address.go, dtos/address_test.go, models/address.go
=> feat: add ZeroMQ channel and update MQTT channel

common/echo_api_constants.go
=> feat: Add new API routes for notifications

dtos/device.go, dtos/device_test.go, dtos/deviceservice.go, dtos/deviceservice_test.go, dtos/discovereddevice.go, dtos/discovereddevice_test.go, dtos/requests/device.go, dtos/requests/device_test.go, dtos/requests/deviceservice.go, dtos/requests/deviceservice_test.go, dtos/requests/provisionwatcher.go, dtos/requests/provisionwatcher_test.go, dtos/requests/schedulejob.go, dtos/requests/schedulejob_test.go, dtos/schedulejob.go, dtos/schedulejob_test.go
=> fix: Ensure `Properties` field is properly initialized and serialized

.github/dependabot.yml
=> build(all): Run dependabot on daily basis

common/constants.go, dtos/event.go, dtos/event_test.go, dtos/reading.go
The proposal introduces a new global environment variable, EDGEX_OPTIMIZE_EVENT_PAYLOAD, for all EdgeX services. When EDGEX_OPTIMIZE_EVENT_PAYLOAD is set to true, the event payload will be optimized.
- Deploy core service, device-virtual, app service
- Inspect the event message to see whether the payload is reduced.
=> feat: Reduce payload size for device events
